update task cards for uploading missing metrics
Recidiviz/justice-counts pull request #1130
Opened 2024-01-05 17:49 UTC by nichelle-hall

## Description of the change

P0 of the Publisher Notifications project requires that we change the homepage card wording for uploading for a metric.  Title should become “Upload {metric name} Metric” and the “Upload Data” cta should become “Bulk Upload”

<img width="1709" alt="Screenshot 2024-01-05 at 8 45 48 PM" src="https://github.com/Recidiviz/justice-counts/assets/19961693/d7e9feb1-40fa-4670-b607-0e8a355e60bf">

## Related issues

Closes  #1129

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2024-01-05 20:32 UTC, brandon-hills approved these changes
![download](https://github.com/Recidiviz/justice-counts/assets/130382407/1bd2b548-4989-4d22-b9e7-cb5df4b97a9d)

2024-01-05 20:32 UTC, brandon-hills commented on publisher/src/stores/HomeStore.ts
> +    if (!hasMultipleSystemsAndAllSystemsFilter) return `Upload ${title} Metric`; // title;
nit: is the `// title;` comment intentional?

2024-01-05 21:06 UTC, mxosman requested changes

2024-01-05 21:17 UTC, nichelle-hall commented on publisher/src/stores/HomeStore.ts
> +    if (!hasMultipleSystemsAndAllSystemsFilter) return `Upload ${title} Metric`; // title;
no 🙃

2024-01-05 21:55 UTC, mxosman approved these changes
Awesome! LGTM!

<img src="https://media2.giphy.com/media/r2BtghAUTmpP2/giphy.gif"/>

2024-01-05 22:42 UTC, morden35 commented on publisher/src/components/Home/types.ts
> -  uploadData: { label: "Upload Data", path: "upload" },
I feel like there may be documentation floating around (maybe in the help center docs) that we may want to update as well

2024-01-08 16:15 UTC, nichelle-hall commented on publisher/src/components/Home/types.ts
> -  uploadData: { label: "Upload Data", path: "upload" },
I did a quick search in the guide and didn't see the button copy mentioned!

2024-01-08 16:15 UTC, merged

2024-01-08 16:56 UTC, morden35 commented on publisher/src/components/Home/types.ts
> -  uploadData: { label: "Upload Data", path: "upload" },
great! thanks for checking