[Publisher] Agency Settings: Adds offset date picker for email notifications
Recidiviz/justice-counts pull request #1238
Opened 2024-03-13 17:36 UTC by mxosman

## Description of the change

Implements the frontend for the e-mail notification offset date picker by adding an input with copy that displays the offset date.

I included an error state for when the user input is out of bounds and cleaned up the copy before the date picker a little bit. This was done consistent with the current design and not in the style of the upcoming Agency Settings design update so things don't look super off.

https://github.com/Recidiviz/justice-counts/assets/59492998/1e21cba3-492a-4b0b-9048-a4c79047b68c

## Related issues

Closes [#27978](https://github.com/Recidiviz/recidiviz-data/pull/27978)

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2024-03-14 13:06 UTC, lilidworkin reviewed
Looks awesome! Thanks for tackling this @mxosman !

2024-03-14 13:06 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +        Emails from Justice Counts will include a list of the metrics you have
nit, not related to this PR, can we adjust all of the text below the toggle to look like the following:

```
This toggle affects your email settings for <agency name>. If you subscribe, you will receive the following emails:
* Reminders to upload data to Publisher each month
* Confirmations that Automated Bulk Upload attempts were processed by Publisher.

Below, you can choose how soon after the end of each reporting period to receive an upload data reminder email. For instance, if you enter 15, you would receive a reminder to upload any missing data for the month of March on April 15th. 

Enter the number of days after the end of the reporting period to receive a reminder email: <input>

Your next email is scheduled to send on X.
```

2024-03-14 13:06 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Is this right? This is adding the offset to the current date, not the end of the last reporting period, right?

2024-03-14 15:35 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Ah!! Great catch! 🤦  Quick silly question that I am doubting my own answer to - is the last reporting period considered the end of the prior month for all agencies? Or is there something else we take into consideration?

2024-03-14 15:36 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +        Emails from Justice Counts will include a list of the metrics you have
Absolutely! Love the copy changes - reads super clear!

cc'ing @jwhrec & @forrestkim00 as I'm sure we'll need to update the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=10571%3A13082&mode=design&t=dRJp8WQHuFKaHMKZ-1) for when someone tackles the design update for the Agency Settings page.

2024-03-14 16:31 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Also, if we've gone past the date - like say the last reporting period is February, and the input for the offset is 2 days and today is March 14 - it probably doesn't make sense for the UI to read "Your next email is scheduled to send on 3/2/2024.", right or am I overthinking this?

If I'm not overthinking - in these cases, I'm curious when the BE will schedule the email send. If it's something like the following month (e.g. 4/2/2024) - I can update the UI logic to match that (check if we've passed the date and if so, go to the next month).

2024-03-14 16:52 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
[Added a screenshot of the updated copy and correct offset date in my first comment in this thread]

2024-03-15 01:02 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +        Emails from Justice Counts will include a list of the metrics you have
OMG lol I didn't realize there was already a Figma for this and that I'm shamelessly overriding @jwhrec and @forrestkim00 here! I just found the existing copy a little confusing and figured it's better to just be SUPER explicit. Jessica/Forrest lmk what you guys think!!

2024-03-15 01:08 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Yea @mxosman these are great callouts, this is actually pretty confusing, I'm not sure the FE should even try to calculate this. I mean, this kind of logic is exactly what @nichelle-hall 's BE had to grapple with!

I think it's even more complex than this -- e.g. if your offset is 60, that means you get emails 2 months after the end of each reporting period, but we can't say that your next email is scheduled ~2 months away. You'll actually get your next email at the end of the _current_ month, it's just that this email will be reminding you about missing metrics from two months ago!

I would vote just to remove this. I think hopefully the updated copy with the example should make it clear enough...

Maybe you can post in Slack with 1) a screenshot of the new copy I suggested to see if Jessica/Forrest are okay with how I hijacked that 😅 and 2) a quick explanation of why it's tricky to calculate the date of the next send, and whether it's okay to remove this?

2024-03-15 01:15 UTC, lilidworkin reviewed
I'll let @nichelle-hall do the final review/approval (and you guys should also test this e2e to make sure the value is getting stored properly)!

I've also asked @nichelle-hall to think about hosting a playtesting session, though I think it's fine to merge this change in before. Obviously playtesting this is a little tricky because we can't wait X days to see if the emails get sent, but I think there are various ways to hack around it, and maybe you can help her brainstorm? For instance, we could have everyone pick an agency and choose an offset, and then maybe we could run the script (in dry run mode) with a flag that "pretends" it's a certain date in the future and prints out which emails it would send.

E.g., suppose I pick 15 as my offset, Michelle picks 45, and Forrest picks 10. Then we run the script with the date set to April 15. It _should_ output that it 1) sends me an email about missing metrics in March, 2) sends Michelle an email about missing metrics from February, and 3) doesn't send Forrest an email at all. Then we can run the script again with the date sent to, say, Jan 10, and it should say it is sending Forrest an email about missing metrics from both the month of December and the previous calendar year. etc...

2024-03-15 16:27 UTC, nichelle-hall commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Just wanted to second what Lili said! When the number is less than the length of an average month, we can display the date of the next email accurately. So in your case above, the email would be 4/2/2024 and not 3/2/2024. But what Lili pointed out is correct, if the offset is greater than the length of an average month than it's a lot more difficult to display that information accurately and in a way that is super clear to the user!

2024-03-15 16:28 UTC, nichelle-hall commented
I'm gonna play with this e2e like Lili suggested and get back to you!

2024-03-15 16:33 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +        Emails from Justice Counts will include a list of the metrics you have
Oh no worries at all! I think with things in flux right now (i.e. w/out the design changes implemented), we can totally ship it this way until then - it's definitely an improvement of the previous copy. I was mostly thinking to memorialize this + Jessica/Forrest's magic in the Figma so when someone works on those design updates it doesn't get overwritten!

2024-03-15 16:33 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Ah - my head! Haha - wow, you are not kidding about the complexity! Totally in favor of removing anything that'll create more confusion here.

>Maybe you can post in Slack with 1) a screenshot of the new copy I suggested to see if Jessica/Forrest are okay with how I hijacked that 😅 

Haha, will do!

> and 2) a quick explanation of why it's tricky to calculate the date of the next send, and whether it's okay to remove this?

As far as explaining why it's tricky - I'm still a little confused myself with the copy and the example above:

>Copy: 
> Below, you can choose how soon after the end of each reporting period to receive an upload data reminder email. For instance, if you enter 15, you would receive a reminder to upload any missing data for the month of March on April 15th.
Enter the number of days after the end of the reporting period to receive a reminder email:

> Example:
> e.g. if your offset is 60, that means you get emails 2 months after the end of each reporting period, but we can't say that your next email is scheduled ~2 months away. You'll actually get your next email at the end of the current month, it's just that this email will be reminding you about missing metrics from two months ago!

Just to try to understand - if the current date is March 15, and I input 60 - I would receive an email at the end of this month (not in 2 months), and that email will include a reminder of missing metrics from 2 months ago, am I understanding this right? If so, I'm not sure I understood that from the copy - as the copy felt like it was only talking about when the reminder email would be sent and not how far back it will go as far as giving a time-window into your missing metrics. Unless, the reminder email naturally covers the offset period?

2024-03-15 16:33 UTC, mxosman commented
> I'll let @nichelle-hall do the final review/approval (and you guys should also test this e2e to make sure the value is getting stored properly)!
> 
> I've also asked @nichelle-hall to think about hosting a playtesting session, though I think it's fine to merge this change in before. Obviously playtesting this is a little tricky because we can't wait X days to see if the emails get sent, but I think there are various ways to hack around it, and maybe you can help her brainstorm? For instance, we could have everyone pick an agency and choose an offset, and then maybe we could run the script (in dry run mode) with a flag that "pretends" it's a certain date in the future and prints out which emails it would send.
> 
> E.g., suppose I pick 15 as my offset, Michelle picks 45, and Forrest picks 10. Then we run the script with the date set to April 15. It _should_ output that it 1) sends me an email about missing metrics in March, 2) sends Michelle an email about missing metrics from February, and 3) doesn't send Forrest an email at all. Then we can run the script again with the date sent to, say, Jan 10, and it should say it is sending Forrest an email about missing metrics from both the month of December and the previous calendar year. etc...

Sounds great to me! Happy to help brainstorm -- I'll need to spend a bit more time trying to wrap my head around the BE and this feature as a whole to be a bit more helpful! I like your suggestion so far - it makes sense to me. Will give this all more thought and make sure that it's saving E2E (when refreshing, the response from the GET request so far appears to have the saved value, but we'll check other areas too, like the DB, etc.).

2024-03-15 17:14 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
That's right! Definitely open to ways to make the copy clearer. The offset applies to each/any reporting period. So an offset of 60 means that 60 days after any reporting period, you'll get an email. Since March 30 is 60 days after the end of the Jan reporting period, you'll get an email then. This is definitely a bit mind melting :)

2024-03-15 17:57 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Gotcha! And just to confirm the email I receive on March 30 will tell me about missing metrics in the Jan reporting period, right? Sorry - thank you for bearing with me, I think I'm starting to understand!

2024-03-15 18:22 UTC, lilidworkin commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
That's right! Since the Jan reporting period ends on Jan 30, and then + 60 days takes you to March 30

2024-03-15 18:38 UTC, mxosman commented on publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
> +  offsetDate.setDate(offsetDate.getDate() + Number(currentOffsetDays));
Thank you so much for the explanation, Lili!

2024-03-18 20:13 UTC, nichelle-hall commented
I ran into a bug! I documented it in this Loom. 

https://github.com/Recidiviz/justice-counts/assets/19961693/3e77136d-621c-4f2d-a0c9-6b7f4660aa93

So far it works E2E, but I'm not able to change the value to test as thoroughly as I want. 
How I'm testing: 
1) Deploying my BE PR and this FE PR to [nichelletest](https://nichelletest---publisher-web-b47yvyxs3q-uc.a.run.app)
2) Updating my offset on a new agency
3) Running [the job](https://console.cloud.google.com/run/jobs/details/us-central1/upload-reminder-email-job/logs?project=justice-counts-staging) in staging
4) Confirming that an email was sent with the correct missing metrics

2024-03-18 21:00 UTC, mxosman commented
> I ran into a bug! I documented it in this Loom.
> 
>  Justice.Counts._.Publisher.-.18.March.2024.mp4 
> So far it works E2E, but I'm not able to change the value to test as thoroughly as I want. How I'm testing:
> 

Ah - dang! Thanks for catching - let me see what I goofed up.

2024-03-18 21:24 UTC, mxosman commented
OK, @nichelle-hall - should be fixed now! I went a little too hard on ensuring there was a value present.

2024-03-19 15:25 UTC, mxosman commented
Hi @nichelle-hall! I couldn't do it via the Github UI - but just re-requesting a review/approval whenever you have a moment.

2024-03-19 15:27 UTC, nichelle-hall approved these changes
I played around with it and it's working great! 

<img src="https://media3.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif"/>

2024-03-19 15:34 UTC, nichelle-hall requested changes
Oh! Actually can we gate this to just recidiviz folks until we launch / playtest?

2024-03-19 16:43 UTC, mxosman commented
> Oh! Actually can we gate this to just recidiviz folks until we launch / playtest?

Oo - good call! I just gated it to staging and local.

2024-03-19 16:45 UTC, nichelle-hall approved these changes
Thank you!

2024-03-19 19:09 UTC, mxosman commented
<img src="https://media4.giphy.com/media/3ohs4kI2X9r7O8ZtoA/giphy.gif"/>

2024-03-19 19:09 UTC, merged