[Publisher] refetch agencies every time that they are edited in the admin panel
Recidiviz/justice-counts pull request #1421
Opened 2024-07-03 21:25 UTC by nichelle-hall

## Description of the change

This update enhances the front-end functionality to refetch agency data after any updates to an agency. This ensures that any changes made to a super agency are accurately reflected in its child agencies.

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2024-07-05 13:52 UTC, mxosman approved these changes
LGTM!

2024-07-05 13:55 UTC, lilidworkin reviewed
Hold on @mxosman @nichelle-hall -- would like to understand this a bit better, since it seems like we were deliberately _not_ doing this previously and instead controlling it via a `refetch` parameter.

So why the change? And is it better just to isolate the place where we do need this, and pass a value of `refetch = true` in that case?

2024-07-05 14:29 UTC, mxosman commented
> Hold on @mxosman @nichelle-hall -- would like to understand this a bit better, since it seems like we were deliberately _not_ doing this previously and instead controlling it via a `refetch` parameter.
> 
> So why the change? And is it better just to isolate the place where we do need this, and pass a value of `refetch = true` in that case?

Hi Lili! Thanks for calling this out! Previously, we were setting the `refetch` to true only when there was an update to the superagency/child agency list so those changes propagate throughout all super/child agencies (the other option at the time was to add more logic to update the FE states of all of the child agencies/superagencies that were modified - but we opted just to refetch because it was simpler and gave us a reliable up-to-date copy of everything). 

Now that the need is for any updates to propagate to superagencies and child agencies, I felt comfortable with us widening the refetch to everything (despite it not being the most optimal solution) since that's probably the simplest way to ensure all the dependencies of your changes are reflected after your hit save. But, now that I'm thinking about this some more after your comment, if this change is motivated just by updating user information and having that propagate, we can totally keep the `refetch` logic as you suggested, and actually just update this flag below to include `hasTeamMemberOrRoleUpdates`:

https://github.com/Recidiviz/justice-counts/blob/4492eda02b1f1741d43398addf77467544375dc8/publisher/src/components/AdminPanel/AgencyProvisioning.tsx#L313

I agree this is a better way to handle this - instead of refetching everything, continue to isolate it until we reach the point where we need every update to propagate. Sorry, I didn't think this through all the way when I was reviewing.

[And, if we do eventually remove the `refetch`, we should remove it from everything (the param in the save function and the AgencyProvisioning component)]

2024-07-05 14:31 UTC, mxosman requested changes
Gently rescinding my approval in favor of Lili's consideration & suggestion. Sorry for the hasty approval!

2024-07-05 15:17 UTC, lilidworkin commented
Awesome, thank you for taking another look at this @mxosman and for the super detailed explanation! That path forward makes perfect sense to me, appreciate it.

2024-07-08 16:08 UTC, nichelle-hall commented
Updated video!

https://github.com/Recidiviz/justice-counts/assets/19961693/9e595296-6b74-400a-955a-a8cbda192dc9

2024-07-08 18:45 UTC, mxosman approved these changes
This looks good to me, Nichelle! Thank you for the adjustments and the video - and thank you for the recommendation, Lili!

2024-07-08 19:26 UTC, merged