[Publisher][Admin Panel] Add Agency URL and Description Fields to Admin Panel
Recidiviz/justice-counts pull request #1582
Opened 2024-11-06 10:51 UTC by nasaownsky

## Description of the change

Added Agency URL and Description Fields to Admin Panel

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1554 

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2024-11-12 00:10 UTC, mxosman approved these changes

2024-11-12 07:35 UTC, nasaownsky commented on publisher/src/components/AdminPanel/AgencyProvisioning.tsx
> +      updateAgencyURL(url);
This totally makes sense!

2024-11-12 14:54 UTC, nichelle-hall commented
Hi @nasaownsky - The BE has been merged. Feel free to merge the PR.

2024-11-12 22:00 UTC, mxosman requested changes
Actually @nasaownsky - there's a bug when you try to delete those fields in the admin panel that seems unrelated to the latest commit. Can you take another look please?

2024-11-13 09:37 UTC, nasaownsky commented
>there's a bug when you try to delete those fields in the admin panel that seems unrelated to the latest commit. Can you take another look please? You should be able to delete those fields entirely.

Oh, you're right, seems like it's the old bug, because it is also affects `Name` field. It is not critical for it though since it's required field, but I can see the edge case when someone wants to totally rename an agency and can't entirely delete its name, so I fix it as well. Please check this changes!

2024-11-13 14:53 UTC, mxosman commented on publisher/src/components/AdminPanel/AgencyProvisioning.tsx
> +      updateAgencyURL(URLValue);
Wonderful idea to send it all at the end!

2024-11-13 14:55 UTC, mxosman approved these changes
> > there's a bug when you try to delete those fields in the admin panel that seems unrelated to the latest commit. Can you take another look please? You should be able to delete those fields entirely.
> 
> Oh, you're right, seems like it's the old bug, because it is also affects `Name` field. It is not critical for it though since it's required field, but I can see the edge case when someone wants to totally rename an agency and can't entirely delete its name, so I fix it as well. Please check this changes!

Ah, good catch! Super vaguely recall the name field one might've been intentional before we implemented blocking the saving to make sure folks couldn't save with an empty name field - but I might be misremembering. Thank you so much for fixing both!! Truly appreciate it. Looks great to me!

2024-11-13 16:51 UTC, nasaownsky commented
Thank you so much, @mxosman!

2024-11-13 16:52 UTC, merged