[WIP] Report Frequency
Recidiviz/justice-counts pull request #199
Opened 2022-12-03 03:53 UTC by mxosman

## Description of the change

> Description here

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-12-06 15:31 UTC, mxosman commented
There's a weird flakey bug that only appears to be happening on my end (curious if anyone else can repro) where some of the metrics aren't saving properly:


https://user-images.githubusercontent.com/59492998/205954548-f6b70715-4325-4cd0-bfb9-ec54b45e0a60.mov

2022-12-06 21:34 UTC, terryttsai approved these changes

2022-12-06 21:34 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +    metadata?: { [key: string]: string | number | null }
Should the keys of the metadata be typed? like 
```
label: string;
description: string;
...
```

2022-12-06 21:34 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +    reenableMetric?: boolean
Maybe we can just have `updateMetricReportFrequency` always set enabled to true? is there a case of updating the metric frequency but we want the metric to stay disabled?

2022-12-06 21:34 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      this.updateMetricEnabledStatus(system, metricKey, true);
It's a little confusing to me that `updateMetricEnabledStatus` is also used to initialize the metric config's info values, I'm thinking there should be a `updateMetric` that takes in any keys, then `updateMetricEnabledStatus` uses that function to specifically set the `enabled` key. 

Like
```
updateMetricEnabledStatus = (
    system: AgencySystems,
    metricKey: string,
    enabledStatus: boolean,
  ): MetricSettings => {
  return this.updateMetric(system, metricKey, { enabled: enabledStatus });
}
```

Then `updateMetric` can be used when initializing all the other values

2022-12-06 22:29 UTC, terryttsai commented
Sorry, I accidentally approved when I meant to leave comment :P

2022-12-06 22:30 UTC, terryttsai requested changes
Sorry, I meant to comment rather than approve!

2022-12-06 22:53 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
is this because these fields are optional? do they have to be optional?

2022-12-06 23:35 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      this.updateMetricEnabledStatus(system, metricKey, true);
Or we can just have the `updateMetric` function, we don't need `updateMetricEnabledStatus`

2022-12-07 17:45 UTC, mxosman commented on publisher/src/components/MetricConfiguration/Configuration.tsx
> +    const frequency = metrics[systemMetricKey]?.frequency;
Yeah, I ran into a crash because `metrics[systemMetricKey]` - total guess - but I think now that we have everything routed through URLs, there maybe a brief moment where metrics[systemMetricKey] is `undefined` before it goes through initialization.

2022-12-07 17:46 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
When there is no `customFrequency` the backend sends an empty string.

2022-12-07 17:47 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +    metadata?: { [key: string]: string | number | null }
I don't think so? I think we kept this purposefully typed in a flexible way so we can pass in any new property that needs rendering - this is just the first time and only in this function's `metadata` that we will receive `number` and `null`.

2022-12-07 17:47 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +    reenableMetric?: boolean
Great idea! I wasn't sure if always sending `enabled` even when the status is already enabled (say you've already selected "Monthly" - and you go to select "Annual") would be suboptimal.

2022-12-07 17:47 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +      this.updateMetricEnabledStatus(system, metricKey, true);
I'm not sure I 100% agree. Originally when we set up these functions, we realized a need to initialize values in the store that will be rendered - and the simplest solution we agreed on was passing in an optional `metadata` (which is never run if not passed in). All of the other pieces aside from the metadata logic are crucial - not sure we can just get away with an `updateMetric` that doesn't have the same core pieces we thought out beforehand.

Please let me know if I'm misunderstanding!

2022-12-07 17:47 UTC, lilidworkin commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
Would it help if the backend sent None instead? That feels more correct to me?

2022-12-07 17:48 UTC, lilidworkin commented on publisher/src/components/MetricConfiguration/Configuration.tsx
> +    const frequency = metrics[systemMetricKey]?.frequency;
I'm also not sure about this, we just kept it the same on the backend to minimize the number of changes, but it is true that it could cause confusion. I don't feel strongly.

2022-12-07 17:51 UTC, lilidworkin commented on publisher/src/stores/MetricConfigStore.tsx
> +    reenableMetric?: boolean
I think that's fine -- hopefully the backend is smart enough not to do extra work here, and if not, that's really the backend's problem!

2022-12-07 17:52 UTC, lilidworkin commented
@mxosman no rush on this but let me / @nichelle-hall  know if you're able to deploy to playtesting and repro the bug there! And if so, tell us which agency/metrics to use to repro and we'll look into it!

2022-12-07 18:12 UTC, mxosman commented on publisher/src/components/MetricConfiguration/Configuration.tsx
> +    const frequency = metrics[systemMetricKey]?.frequency;
I'm personally leaning towards minimizing the # of changes - but don't feel strongly either.

2022-12-07 18:14 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
We can do `None`! I agree with it feeling more correct than an empty string.

2022-12-07 18:15 UTC, mxosman commented
> @mxosman no rush on this but let me / @nichelle-hall know if you're able to deploy to playtesting and repro the bug there! And if so, tell us which agency/metrics to use to repro and we'll look into it!

Will do!

2022-12-07 18:15 UTC, lilidworkin commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
Great! @nichelle-hall can you make that change?

2022-12-07 18:20 UTC, mxosman commented
> @mxosman no rush on this but let me / @nichelle-hall know if you're able to deploy to playtesting and repro the bug there! And if so, tell us which agency/metrics to use to repro and we'll look into it!

OK - great news - I've tried a few agencies and all their metrics and haven't been able to repro! You will see in some areas when you first load a metric - it might by in a funky state, but you can disable and reenable the metric and things work just fine. Would love a sanity check if folks have time/bandwidth!

Here's the playtesting link: https://playtesting---justice-counts-web-qqec6jbn6a-uc.a.run.app

2022-12-07 18:25 UTC, mxosman commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
Only if it doesn't complicate things in the backend - both empty string and null will be falsy - so it won't make a huge difference!

2022-12-07 18:29 UTC, lilidworkin commented
Awesome, thanks @mxosman ! I also checked it out briefly and wasn't able to repro, but I'll spend a little more time playing around with it later.

2022-12-07 23:46 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      this.updateMetricEnabledStatus(system, metricKey, true);
Maybe this proposal makes more sense: 

Instead of having `updateMetricEnabledStatus` handle both changing the metric enabled AND initializing metric metadata, we create a separate `initializeMetric` function like so:

```
  initializeMetric = (
    system: AgencySystems,
    metricKey: string,
    metadata: { [key: string]: string | number | null }
  ) => {
    const systemMetricKey = MetricConfigStore.getSystemMetricKey(
      system,
      metricKey
    );

    /** Initialize nested object for quick lookup and update and reduce re-renders */
    if (!this.metrics[systemMetricKey]) {
      this.metrics[systemMetricKey] = {};
    }

    /** Add metadata required for rendering */
    this.metrics[systemMetricKey].label = metadata.label as string;
    this.metrics[systemMetricKey].description = metadata.description as string;
    this.metrics[systemMetricKey].defaultFrequency =
      metadata.frequency as ReportFrequency;
    this.metrics[systemMetricKey].customFrequency =
      metadata.customFrequency as ReportFrequency;
    this.metrics[systemMetricKey].startingMonth = metadata.startingMonth as
      | number
      | null;
  };
```

then `updateMetricEnabledStatus` can be simplified to just only updating the metric enabled state?

Originally I was thinking of some base-level `updateMetric` function that is shared between these different update functions but how does this proposal sound?

2022-12-08 00:03 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +    metadata?: { [key: string]: string | number | null }
So I see a lot of casting as string and null going on here, and I also see the `label, description, frequency, customFrequency, startingMonth` params being redefined often. I think in a follow-up PR this could be cleaned up, something like: https://github.com/Recidiviz/justice-counts/commit/e7a5ac75147af607b0ee956ab1064bc4da6c5abd

By typing metadata into these specific keys, then I no longer have to cast all the metadata as string or ReportFrequency for each key. I hadn't taken a good look to understand the system in place so let me know if this is totally off the mark with what you're going for!

2022-12-08 00:04 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
Hey so perhaps in a follow-up PR I'm wondering if we can change the type around such that we won't need to cast as string here: https://github.com/Recidiviz/justice-counts/commit/e7a5ac75147af607b0ee956ab1064bc4da6c5abd

2022-12-08 00:06 UTC, terryttsai approved these changes
This system looks good to me, thanks for reasoning out and dealing w all the complexity here! I answered your question to my feedback and left a quick proposal for possible further type improvements in the future, though I hadn't looked at this long enough to know if what I'm proposing makes sense for this feature. Let's get this merged in!

2022-12-08 00:08 UTC, terryttsai commented
Oh the commit I put up https://github.com/Recidiviz/justice-counts/commit/e7a5ac75147af607b0ee956ab1064bc4da6c5abd also includes the `initializeMetric` I was alluding to [here](https://github.com/Recidiviz/justice-counts/pull/199#discussion_r1042787730), the next step down that route is to use that method for initialization, and remove `metadata` from `updateMetricEnabledStatus`

2022-12-08 16:57 UTC, mxosman commented on publisher/src/components/MetricConfiguration/Configuration.tsx
> +    const frequency = metrics[systemMetricKey]?.frequency;
I wonder if we'll run into `systemMetricKey` being undefined with the new changes in main - since entering an invalid/empty value for metric/system in params gets autocorrected.

2022-12-08 19:13 UTC, merged

2022-12-08 20:31 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      customFrequency?: Metric["custom_frequency"] | string;
Looks good!

2022-12-08 20:32 UTC, terryttsai commented on publisher/src/stores/MetricConfigStore.tsx
> +      this.updateMetricEnabledStatus(system, metricKey, true);
Thanks for making the task for it! Glad it makes sense after I had some thought to write it out!