Review page refresh
Recidiviz/justice-counts pull request #507
Opened 2023-03-16 17:23 UTC by ivan-kishko

## Description of the change

> New design for review page for:
1. Data entry
2. Bulk publish/unpublish
3. spreadsheet upload

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #481 

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-03-16 20:50 UTC, hobuobi requested changes
Leaving a few comments with suggested changes! 
- General: 
    - Definitely need a responsive version as a follow-up. Not blocking the merge though. 
- When you hit “Publish”: 
    - I don’t think we need both the toast and the modal. Just the modal is fine.
    - It would be great if hitting “Go to Data” took you to one of the metrics you were just looking at (for example, the first metric on the Review page you were just looking at). 
- Top bar: 
    - I think the current version has some option other than Publish in the top bar? Seems strange that we only have Publisher up there; would expect a "Save and Exit" for now or something. 
    - This wasn’t technically within scope, but I don’t know why we have the “Continue” and “New Upload” buttons in the body of the page instead of the navigation bar (next to “Cancel”). Seems inconsistent and a little unintuitive right now. 
- Summary: 
    - When we’re publishing less than maybe 10 records, it would be great to keep the list expanded. If more than ten, default to collapsed view. 
- Data: 
    - Need a better treatment for metrics that have long names – at the very least, the full name should be visible on hover (via tooltip? by hiding the date labels? etc) 
    - If there’s no data for a metric, it would be better to have a collapsed empty state for the section, rather than take up more space on the page with empty data. 
        - Same thing with breakdowns with no data; I would like to collapse these if there’s nothing relevant. I feel this pain especially with the Race/Ethnicity numbers. 
    - Expected to have the date label in the data table change colors or something when you hover over a column. Would help to know which date I’m highlighting / focusing on! (Maybe blue label with white text?) 
- Basic Functionality
    - I keep running into an issue where the data takes a long time to show up in the page! The Review page will show up with no data, and then it will populate a few seconds later. Not sure what’s up with this. 
    - “No Metrics to Review” page still has a Publish button? Shouldn’t be there – probably a Cancel or Return button.

2023-03-17 10:58 UTC, ivan-kishko commented
> When you hit “Publish”:
> * I don’t think we need both the toast and the modal. Just the modal is fine.

[3b7ebc9](https://github.com/Recidiviz/justice-counts/pull/507/commits/3b7ebc9b2368e056d94ae32d0d8b22c7abf608fb)

2023-03-17 11:41 UTC, ivan-kishko commented
> * It would be great if hitting “Go to Data” took you to one of the metrics you were just looking at (for example, the first metric on the Review page you were just looking at).

[28f6951](https://github.com/Recidiviz/justice-counts/pull/507/commits/28f6951b1720fb27b2a0cddfbd6f64565e3de43b)

2023-03-17 11:42 UTC, ivan-kishko commented
> * I keep running into an issue where the data takes a long time to show up in the page! The Review page will show up with no data, and then it will populate a few seconds later. Not sure what’s up with this.

[3f4909a](https://github.com/Recidiviz/justice-counts/pull/507/commits/3f4909a075ea1633fa6a96a06a863ab527aea20e)

2023-03-17 11:47 UTC, ivan-kishko commented
> Summary:
> * When we’re publishing less than maybe 10 records, it would be great to keep the list expanded. If more than ten, default to collapsed view.

[0d32cce](https://github.com/Recidiviz/justice-counts/pull/507/commits/0d32cce99d3432650f98a3db0024b90e0bac034d)

2023-03-17 14:18 UTC, ivan-kishko commented
> Top bar:
> * I think the current version has some option other than Publish in the top bar? Seems strange that we only have Publisher up there; would expect a "Save and Exit" for now or something.
> * This wasn’t technically within scope, but I don’t know why we have the “Continue” and “New Upload” buttons in the body of the page instead of the navigation bar (next to “Cancel”). Seems inconsistent and a little unintuitive right now.



> * “No Metrics to Review” page still has a Publish button? Shouldn’t be there – probably a Cancel or Return button.

Hello @hobuobi. Can you please specify which review page you referring to in this bullet points. I am not sure I understand. Thanks

> * Same thing with breakdowns with no data; I would like to collapse these if there’s nothing relevant. I feel this pain especially with the Race/Ethnicity numbers.

And I dont think I understand the idea behind this one

2023-03-17 15:54 UTC, ivan-kishko commented
> * Need a better treatment for metrics that have long names – at the very least, the full name should be visible on hover (via tooltip? by hiding the date labels? etc)

Because of how table works on HTML it is kinda hard to do both. For now I added title tag so full name is seen via small tooltip after a second or two.  If you want something specific I think I need a design so I am not wasting time on something that can be disapproved

 [bfdae37](https://github.com/Recidiviz/justice-counts/pull/507/commits/bfdae37a6be940d91347daf1dad76266491f8969)

2023-03-17 15:57 UTC, ivan-kishko commented
> * If there’s no data for a metric, it would be better to have a collapsed empty state for the section, rather than take up more space on the page with empty data.

How should collapsed state look? I mean that metric name and dates that are on a same row are both part of a DataTableViewComponent. Should it be like only metric name with plus sign? Or what are you thinking about?

2023-03-18 14:36 UTC, lilidworkin reviewed
Hi @ivan-kishko (cc @hobuobi , @mxosman ):

This is all looking great! I have a bunch of comments/ideas though.

## Code Organization

My main comment about the code is this: currently you have three different components for the Review Page, one for each place where it appears:

* `PublishConfirmation.tsx` appears after clicking Review from a single record
* `BulkActionReviewConfirmation.tsx` appears after clicking Bulk Publish from Records page
* `ReviewMetrics.tsx` appears after Bulk Upload

**Can we consolidate these three files into one?** Or at least, can we have a shared component that all three files rely on? The look and feel of the page should be almost identical in these three places. That way we can re-use more code and prevent duplication, and we can ensure the behavior of the page stays consistent. 

Let me know if this is going to be very hard. I'm also curious to hear @mxosman 's thoughts on it.

## Humphrey's Comments

> Definitely need a responsive version as a follow-up. Not blocking the merge though.

I think there is a design for a responsive version [here](https://www.figma.com/file/brkAAatBCcvSnLJOIxZJIM/recidiviz-x-allison?node-id=883-3730&t=0a8nCmAPCGlH815N-0) in Figma. Ivan, is that enough for you to work from?

> “No Metrics to Review” page still has a Publish button? Shouldn’t be there – probably a Cancel or Return button.

Humphrey is talking about when the Review Page appears after Bulk Upload. If you upload a blank, empty template, the page looks like this. Since there’s no data, instead of Publish, it should say Close (that’s the same as the current behavior on main). And the modal shouldn’t appear. Thanks!

<img width="313" alt="Screenshot 2023-03-18 at 10 00 48 AM" src="https://user-images.githubusercontent.com/99899591/226112239-7d4c6bef-3185-493e-9c5f-4219e7355568.png">

> When we’re publishing less than maybe 10 records, it would be great to keep the list expanded. If more than ten, default to collapsed view.

Ivan, your fix to this looks great! I think there is one edge case though — when you publish a single record directly from the Record page, it looks like this section is still collapsed by default. 

>  I think the current version has some option other than Publish in the top bar? Seems strange that we only have Publisher up there; would expect a "Save and Exit" for now or something.

In my task for Ivan, I told him not to worry too much about the top bar, because some of this depends on the backend changes that Mahmoud is going to make. But to clarify/summarize, let me break this down by the different types of review pages:
1. Single Record Page —> Review page 
    1. The buttons that appear are “Back to Data Entry”, “Exit Without Publishing”, and “Publish”. **Let’s keep these as they are!**
2. Records Page —> Bulk Publish —> Review Page
    1. The buttons that appear are “Cancel” and “Publish”. **Let’s change “Cancel” to “Exit Without Publishing”. The functionality should stay the same.**
3. Bulk Upload —> Review Page
    1. The buttons that currently appear are just “Publish”. **Let’s also add an “Exit Without Publishing” button that takes you to the Records page.**

> 	Need a better treatment for metrics that have long names – at the very least, the full name should be visible on hover (via tooltip? by hiding the date labels? etc)

I think we can address this in a follow-up PR — I’ll make a ticket to come back to it.

> 	If there’s no data for a metric, it would be better to have a collapsed empty state for the section, rather than take up more space on the page with empty data.Same thing with breakdowns with no data; I would like to collapse these if there’s nothing relevant. I feel this pain especially with the Race/Ethnicity numbers.

I think we can address these in a follow-up PR as well. I'll make a ticket.

## Other thoughts of my own:

1. Do we need to restrict the height of the “Review and Publish” section? Right now it forces you to vertically scroll, even when there is plenty of space left underneath it. I also see a horizontal scrollbar in the right panel, even when there doesn’t need to be.

<img width="467" alt="Screenshot 2023-03-18 at 10 05 56 AM" src="https://user-images.githubusercontent.com/99899591/226112365-06d95916-b3ad-4e57-922a-018ab4501122.png">

2. Small thing -- the design between breakdowns seems different from what is in the Figma, I think? In other words, in the screenshot below, I think there should be more space above "Race/Ethnicity", instead of a line?

<img width="344" alt="Screenshot 2023-03-18 at 10 34 29 AM" src="https://user-images.githubusercontent.com/99899591/226112631-a34566e6-695a-4814-a2ec-c1d080825caa.png">

3. _Very_ small thing -- if you are publishing multiple records, can we change the text "Here’s a breakdown of data from the record." to "Here’s a breakdown of data from the records."

Thank you for all your hard work on this Ivan -- it looks really really good!

2023-03-18 14:36 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
Ah, yes -- I actually wasn't expecting you to do this part, @ivan-kishko ! @mxosman is going to work on a proper solution to this that involves changing our backend. I think this is probably fine for now and @mxosman can just change it later?

2023-03-18 14:36 UTC, lilidworkin commented on publisher/src/pages/Reports.tsx
> +                      {bulkAction === "publish" && selectedRecords.length > 0 && (
Sorry for the confusion @ivan-kishko -- I actually wasn't expecting you to do this part. @mxosman is working on the backend piece for when the user hits Publish or Unpublish here. I think it's fine to keep this, and @mxosman can change it later? Up to you guys though. In this PR, I was mostly expecting @ivan-kishko just to focus on redesigning the Review Page where it _currently_ appears (after publishing a single Record, and after Bulk Upload), not adding it to appear in this third place (after Bulk Publishing). Sorry for not being more clear about this!

2023-03-20 12:50 UTC, ivan-kishko commented
> 1. Do we need to restrict the height of the “Review and Publish” section? Right now it forces you to vertically scroll, even when there is plenty of space left underneath it. I also see a horizontal scrollbar in the right panel, even when there doesn’t need to be.

Hello @lilidworkin. Yes I kinda have to do that because for desktop view this part of page is fixed position and if I won't restrict its height and there will be a lot of records/metrics it will overlap with itself left part of the footer. I make its height a bit bigger but max height will be 48px above footer (since we decided that it will be the min space between footer and content above)

2023-03-20 14:27 UTC, ivan-kishko commented
> I think there is a design for a responsive version [here](https://www.figma.com/file/brkAAatBCcvSnLJOIxZJIM/recidiviz-x-allison?node-id=883-3730&t=0a8nCmAPCGlH815N-0) in Figma. Ivan, is that enough for you to work from?
> 
> >

It is but I will make it go vertical from min desktop width (1200px i guess) instead of 700px like it is in figma since just summary is 500px wide therefore on 700 px only part of names in table will be seen

2023-03-20 14:58 UTC, lilidworkin commented
> About this - the main reason this is 3 different pages is that they receive different type of data and in a different way. But I think I can come up with something or maybe @mxosman can suggest something as well. One thing if it matters - these pages are using the same styled components (like i dont remember maybe there are few components that are changed depending on a page but generally they are all the same)

I think we should do our best to try and see how it goes! It's not the styles I'm worried about, it's the functionality. 

What if they all have their own component that converts the different types of data into one shared type of data, and then passes that into a shared component?

2023-03-20 14:58 UTC, lilidworkin commented
> Hello @lilidworkin. Yes I kinda have to do that because for desktop view this part of page is fixed position and if I won't restrict its height and there will be a lot of records/metrics it will overlap with itself left part of the footer.

Is there no way to have it know where the footer starts, and only scroll if it would overlap with the footer?

2023-03-20 15:09 UTC, ivan-kishko commented
> > Hello @lilidworkin. Yes I kinda have to do that because for desktop view this part of page is fixed position and if I won't restrict its height and there will be a lot of records/metrics it will overlap with itself left part of the footer.
> 
> Is there no way to have it know where the footer starts, and only scroll if it would overlap with the footer?

Hello!) Please check latest commit I think this is the best I can do. Well to be honest I can make bottom padding to be slightly above footer (less than footer margin) but it still be here regardless of footer seen or not. And no, this is not how fixed positioned elements work. They basically removed from DOM flow and do not know anything about other elements properties. 

https://developer.mozilla.org/en-US/docs/Web/CSS/position#:~:text=with%20other%20margins.-,fixed,element%20is%20placed%20in%20the%20same%20position%20on%20every%20page.,-sticky

2023-03-20 15:22 UTC, ivan-kishko commented
> > Hello @lilidworkin. Yes I kinda have to do that because for desktop view this part of page is fixed position and if I won't restrict its height and there will be a lot of records/metrics it will overlap with itself left part of the footer.
> 
> Is there no way to have it know where the footer starts, and only scroll if it would overlap with the footer?

[631c26a](https://github.com/Recidiviz/justice-counts/pull/507/commits/631c26a997fc7d8945c29b50d86ba33efe4802fe) Check out this one

2023-03-20 16:15 UTC, mxosman commented on publisher/src/components/Reports/BulkActionReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
Yes - totally fine with me! That's what I assumed - I think it might've been helpful to receive some form of data (this or mocks) to keep iterating on the design.

2023-03-20 16:15 UTC, mxosman commented on publisher/src/pages/Reports.tsx
> +                      {bulkAction === "publish" && selectedRecords.length > 0 && (
Not a problem at all! Totally good with keeping it as is and me replacing!

2023-03-20 16:25 UTC, mxosman commented
> @lilidworkin Also please review latest commit, I think I fixed all that you pointed out except things that go on another task and responsive design
> 
> > My main comment about the code is this: currently you have three different components for the Review Page, one for each place where it appears:
> > 
> > * `PublishConfirmation.tsx` appears after clicking Review from a single record
> > * `BulkActionReviewConfirmation.tsx` appears after clicking Bulk Publish from Records page
> > * `ReviewMetrics.tsx` appears after Bulk Upload
> > 
> > **Can we consolidate these three files into one?** Or at least, can we have a shared component that all three files rely on? The look and feel of the page should be almost identical in these three places. That way we can re-use more code and prevent duplication, and we can ensure the behavior of the page stays consistent.
> > Let me know if this is going to be very hard. I'm also curious to hear @mxosman 's thoughts on it.
> 
> About this - the main reason this is 3 different pages is that they receive different type of data and in a different way. But I think I can come up with something or maybe @mxosman can suggest something as well. One thing if it matters - these pages are using the same styled components (like i dont remember maybe there are few components that are changed depending on a page but generally they are all the same)

---

> I think we should do our best to try and see how it goes! It's not the styles I'm worried about, it's the functionality.
> 
> What if they all have their own component that converts the different types of data into one shared type of data, and then passes that into a shared component?

---
I definitely think it's worth consolidating these as much as possible. The publish review/confirmation components are the ones I'm least familiar with - so, I don't have any good suggestions to offer at the moment. Since they all look pretty much the same, I would see if there's a central data structure they can all conform to - and if there's a way to transform their data structure, similar to Lili's suggestion - so they can render in the same component. As I dive deeper in the review, I might have more specific suggestions, but that's where my mind would go (finding a way to funnel the 3 different types of data into one that can be easily rendered in one component)

2023-03-20 19:03 UTC, mxosman reviewed
Wow Ivan - this was a lot of work executed beautifully as always! Left a few notes, thoughts, and questions - nothing glaring to me that hasn't been pointed out or that won't be done in a follow up! Loved your solutions & implementations.

2023-03-20 19:03 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +type Overwrite = {
tiny nit: I would change this to something like `MetricOverwrites` for clarity

2023-03-21 11:33 UTC, ivan-kishko commented
@lilidworkin Hello) Check out this one [654f7d3](https://github.com/Recidiviz/justice-counts/pull/507/commits/654f7d35c7ed76e76006adb41ce5ef3b3d708b1d)

2023-03-21 11:36 UTC, ivan-kishko commented on publisher/src/components/Reports/PublishConfirmation.tsx
> +// };
Yeah) Its just, there was so much work done before this redesign and I thought if you want to go back to prev design it is going to be a pain) But I guess i am overthinking and too careful) I will delete all this)

2023-03-21 11:39 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
> +  padding: ${40 + HEADER_BAR_HEIGHT}px 0 128px 612px;
[46c8187](https://github.com/Recidiviz/justice-counts/pull/507/commits/46c818719266bb4282a20a4925c85e0953ac1b20)

2023-03-21 11:41 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +          </ReviewMetricsModalButton>
well it is what design says so up to you

2023-03-21 11:42 UTC, ivan-kishko commented on publisher/src/components/Reports/ReviewPublishModal.tsx
> +};
probably, but will do that after pages

2023-03-21 11:42 UTC, ivan-kishko commented on publisher/src/components/Reports/ReviewPublishModal.tsx
> +};
probably, but will do that after pages

2023-03-21 11:44 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +type Overwrite = {
[20dbcc5](https://github.com/Recidiviz/justice-counts/pull/507/commits/20dbcc5ca5b188f822127be284eec44b7b3b76db)

2023-03-21 12:06 UTC, ivan-kishko commented on publisher/src/components/Reports/ReviewReportDataEntry.tsx
> +      {/* <PublishConfirmationSummaryPanel reportID={reportID} /> */}
[60cfcb0](https://github.com/Recidiviz/justice-counts/pull/507/commits/60cfcb0de4717ca916f4697ccfc645bde88f61e3)

2023-03-21 12:06 UTC, ivan-kishko commented on publisher/src/components/Reports/PublishConfirmation.tsx
> +// };
[60cfcb0](https://github.com/Recidiviz/justice-counts/pull/507/commits/60cfcb0de4717ca916f4697ccfc645bde88f61e3)

2023-03-21 12:06 UTC, ivan-kishko commented on publisher/src/components/Reports/PublishConfirmation.tsx
> +      {/* </ConfirmationDialogueWrapper> */}
[60cfcb0](https://github.com/Recidiviz/justice-counts/pull/507/commits/60cfcb0de4717ca916f4697ccfc645bde88f61e3)

2023-03-21 17:58 UTC, mxosman commented on publisher/src/components/Reports/PublishConfirmation.tsx
> +// };
Ah - thank you for clarifying! Definitely appreciate you looking out! I think it's fine to delete because we can refer to older commits if we want to revive this.

2023-03-21 17:59 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +          </ReviewMetricsModalButton>
No action needed. I'll bring this up during one of our testing sessions - still back and forth. Thanks, Ivan.

2023-03-23 21:52 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +    if (!uploadedMetrics) {
well there is no need for that I guess since if you have not selected any records button for publish/unpublish do not appear

2023-03-24 21:01 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +    if (!uploadedMetrics) {
Ah yes! Great point. Thank you for clarifying.

2023-03-24 23:23 UTC, mxosman reviewed
WOW, Ivan! This was a big undertaking -- I love the way you thought through this and how you consolidated the review and modal components and transformed the data in the other components to seamlessly feed into it. Thank you so much for all of your work on this! Most of my feedback are small nits.

There is one behavior that I wanted to note going from Data Entry to Publish Review -- there's a blip in between when the components are mounting and unmounting that we see a bit of the home page and header. Let me know if you're able to see this as well:

https://user-images.githubusercontent.com/59492998/227659472-b0f7b5b3-af26-4702-b4f9-b4a0e62667c4.mov

Any ideas on what's causing that? It looks like the component doesn't mount until we get a response from the `datapoints` endpoint. Maybe we can let it mount but add a loader (until the `datapoints` endpoint returns a response)? Let me know if I'm not making sense.

Aside from the feedback above - I'll be happy to approve this! I also want to give @lilidworkin a chance to do another pass if she wants to.

2023-03-24 23:23 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +          // TODO(#24): Add Publish button to publish multiple reports at once (todo from upload metrics)
We can delete this whole TODO - I don't think we need this anymore. cc'ing @lilidworkin just to confirm (I can close out task #24 as well if you agree).

2023-03-24 23:23 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +`;
nit: could move these to the .styles.tsx file

2023-03-24 23:23 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +};
nit: no strong feelings - but might be worth moving to a `types.ts` file within this folder

2023-03-26 01:55 UTC, lilidworkin approved these changes
@ivan-kishko , this looks fantastic! I left a few small comments, but after you address those, you can go ahead and merge. I'll file tickets for some of the follow-up work. Thank you so much for all your hard work on this!

> There is one behavior that I wanted to note going from Data Entry to Publish Review -- there's a blip in between when the components are mounting and unmounting that we see a bit of the home page and header. Let me know if you're able to see this as well

I actually wasn't able to repro this! This is what I see:

https://user-images.githubusercontent.com/99899591/227751018-6270573c-63eb-435a-a799-43cdd557b739.mov

In any case @mxosman you're going to have to change around some of this logic, so maybe it's okay? But if @ivan-kishko is able to repro then feel free to fix!


One small thing I did see @ivan-kishko is if you go here, there's some text overlap: http://localhost:3000/agency/161/data?system=jails&metric=jails_funding. Is it possible to have the table column width expand based on the text length? If it's hard, don't worry about it for now.

<img width="500" alt="Screenshot 2023-03-25 at 8 57 29 PM" src="https://user-images.githubusercontent.com/99899591/227750978-83133b52-ad8f-45d8-96e1-cfccbbef36f5.png">

2023-03-26 01:55 UTC, lilidworkin commented on common/hooks/useIsFooterVisible.ts
> +  }
Yea @ivan-kishko thank you so much for this fix! It looks a lot better now that the left side panel isn't fixed height!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +      navigate(
Question (maybe for @mxosman ) -- if only the system param OR the metric param is present, do we want to include them in the URL? Or do we only want to include them if both are present (the current behavior)?

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/pages/Reports.tsx
> +                      {/*  )} */}
+1

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +  const unpublishActionTitle = "Review Unpublish";
+1

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +      name: "Exit without Publishing",
nit -- if you're currently Unpublishing, this should say "Exit without Unpublishing"

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +export const ReviewMetrics: React.FC<ReviewMetricsProps> = ({
@ivan-kishko you did _such_ a good job making this a re-usable component between all 3 review screens! I love the properties you chose to pass into it. Really excellent job thinking it through!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/DataEntryForm.tsx
> +const DataEntryTopBarButton = styled(Button)<{ isSaveInProgress?: boolean }>`
Is the goal of these changes to prevent the user from pressing "Review" when data is currently being saved?

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/DataUpload/UploadReview.tsx
> +  });
Maybe related to @mxosman 's question -- how is the `if (!uploadedMetrics)` check on line 42 different from the one on line 48?

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/DataUpload/UploadReview.tsx
> +  const buttons: ReviewHeaderActionButton[] =
The logic for these buttons looks perfect, thank you for your patience on this!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/DataEntryReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
So this is fine for now and I totally see why you had to add this call here @ivan-kishko , but @mxosman you're going to want/need to refactor this later for performance reasons. We should ideally remove the `datapointsStore.getDatapoints(agencyId)` call from both BulkActionReview and DataEntryReview. This endpoint is really expensive because it pulls _all_ datapoints for an agency. BulkActionReview only needs datapoints for some reports (the ones we are publishing), and DataEntryReview only needs datapoints for one report. So it's overkill to call this method. 

@mxosman I was going to say we could call your new `get_reports_by_id` method instead, and either pass in a list of reports or just a single report, but I actually think that might not quite work. That method returns "metrics" objects, whereas this `getDatapoints` method returns `datapoints` objects, and the review page requires the latter. I think it should be doable to refactor `get_reports_by_id` to return datapoints instead of metrics. Anyway, let me know if you're following my train of thought here and we can discuss further!

But @ivan-kishko you don't have to worry about this, you made the absolute right decision here -- this is the only backend endpoint currently available that does what you need!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/ReviewReportDataEntry.tsx
> -      <PublishConfirmationSummaryPanel reportID={reportID} />
nit, I think we can delete the PublishConfirmationSummaryPanel page as well?

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +            key: metric.key,
Because we don't pass in `metricHasValidInput` here, the checkmarks in the left sidepanel will always be blank circles on the Bulk Action Review page (and same for the Bulk Upload Review page). The Data Entry Review page is the only one that can ever have blue checkmarks.

see for instance:
<img width="506" alt="Screenshot 2023-03-25 at 12 52 00 PM" src="https://user-images.githubusercontent.com/99899591/227750732-419c2e7b-0657-4dcd-a10f-e44a4667ea73.png">

I think we should fix this, but I'll make another ticket for it and we can do it in a follow-up PR!

I think the idea is that the checkmark should be filled if we have data for the top-level metric, is that right @mxosman ? Basically I'm referring to this logic:

```
metricHasValidInput={Boolean(
  formStore.metricsValues?.[reportID]?.[metric.key]?.value
)}
```

So we'd need to figure out an analog of this logic for when you're bulk publishing/uploading a metric over multiple time periods. I guess we'd want to check if, for each time period for which you are uploading the metric, do we have data for the top level metric?

We could also punt on this and just use the blue checkmark in all cases. I'm not opposed to that :D @mxosman why don't you give it some thought and then suggest a path forward to @ivan-kishko ?

Again, not blocking this PR though!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +          // TODO(#24): Add Publish button to publish multiple reports at once (todo from upload metrics)
That's right!

2023-03-26 01:55 UTC, lilidworkin commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +                      {!metricHasError && !metricHasValidInput && <EmptyIcon />}
As discussed in my comment, above, we will always be in the EmptyIcon state unless we are coming to this page from Data Entry. There isn't an obvious fix for this, so let's address in a follow up PR after giving it more thought.

2023-03-26 19:25 UTC, lilidworkin commented on publisher/src/components/Reports/DataEntryReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
Filed ticket for @mxosman [here](https://github.com/Recidiviz/justice-counts/issues/529).

2023-03-26 19:26 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +            key: metric.key,
Filed this ticket for both @mxosman / @ivan-kishko [here](https://github.com/Recidiviz/justice-counts/issues/530). I think @mxosman  can help figure out the right behavior (fine if you want to discuss with Humphrey, but I personally would just pick whatever we think is easiest and sensible), and then @ivan-kishko  can implement!

2023-03-27 11:58 UTC, ivan-kishko commented
> WOW, Ivan! This was a big undertaking -- I love the way you thought through this and how you consolidated the review and modal components and transformed the data in the other components to seamlessly feed into it. Thank you so much for all of your work on this! Most of my feedback are small nits.
> 
> There is one behavior that I wanted to note going from Data Entry to Publish Review -- there's a blip in between when the components are mounting and unmounting that we see a bit of the home page and header. Let me know if you're able to see this as well:
> 
> Any ideas on what's causing that? It looks like the component doesn't mount until we get a response from the `datapoints` endpoint. Maybe we can let it mount but add a loader (until the `datapoints` endpoint returns a response)? Let me know if I'm not making sense.
> 
> Aside from the feedback above - I'll be happy to approve this! I also want to give @lilidworkin a chance to do another pass if she wants to.

Hello @mxosman I know why is that. It is because data entry and review headers are allocated above main header. What you are suggesting is fine but as Humphrey mentioned if you change something in data entry there is like few seconds you see old data in review and then it updates. So it is either load and see main header or no loader and see data changing inside tables. If all pages would have their own header it would not be a problem but our main header is located apart from pages that is why we see it if something like this going on

2023-03-27 13:29 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +      navigate(
well for review pages it is kinda both or none since we review metrics, they will always have a system, if (like in upload) no metrics to review system does not make sense cause you are not able to publish anyway and see whit option in modal

2023-03-27 13:34 UTC, ivan-kishko commented on publisher/src/components/Reports/ReviewReportDataEntry.tsx
> -      <PublishConfirmationSummaryPanel reportID={reportID} />
it is removed already, probably you look at old commit

2023-03-27 14:10 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +`;
[018b930](https://github.com/Recidiviz/justice-counts/pull/507/commits/018b930a0363c9f93b6bbcd0042a8ab02ef21175)

2023-03-27 14:10 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
> +};
[018b930](https://github.com/Recidiviz/justice-counts/pull/507/commits/018b930a0363c9f93b6bbcd0042a8ab02ef21175)

2023-03-27 14:12 UTC, ivan-kishko commented
[f643153](https://github.com/Recidiviz/justice-counts/pull/507/commits/f643153e4687cac02b80c7044adb2ca869f73b8d) fixed table names here @lilidworkin

2023-03-27 14:13 UTC, ivan-kishko commented on publisher/src/components/Reports/BulkActionReview.tsx
> +      name: "Exit without Publishing",
[438efae](https://github.com/Recidiviz/justice-counts/pull/507/commits/438efae8659cc6db3aa3fe552f43af64df18fc1a)

2023-03-27 14:14 UTC, ivan-kishko commented
@hobuobi Hello Humphrey!) I think I need an approve from you to merge this and go on

2023-03-27 16:52 UTC, mxosman commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +      navigate(
At least the way the data page is set up now, not having both will redirect you to the homepage. I wouldn't try to hit this endpoint without having both.

2023-03-27 16:56 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +      navigate(
I think it is not redirect but first system first metric. this function is wrote just to not see undefined in address bar for system and metric

2023-03-27 16:59 UTC, ivan-kishko commented on publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
> +      navigate(
and to not catch an error <code>TypeError: Cannot read properties of undefined (reading 'toLowerCase')</code>

2023-03-27 18:29 UTC, mxosman commented
> > There is one behavior that I wanted to note going from Data Entry to Publish Review -- there's a blip in between when the components are mounting and unmounting that we see a bit of the home page and header. Let me know if you're able to see this as well:
> > Any ideas on what's causing that? It looks like the component doesn't mount until we get a response from the `datapoints` endpoint. Maybe we can let it mount but add a loader (until the `datapoints` endpoint returns a response)? Let me know if I'm not making sense.
> 
> Hello @mxosman I know why is that. It is because data entry and review headers are allocated above main header. What you are suggesting is fine but as Humphrey mentioned if you change something in data entry there is like few seconds you see old data in review and then it updates. So it is either load and see main header or no loader and see data changing inside tables. If all pages would have their own header it would not be a problem but our main header is located apart from pages that is why we see it if something like this going on

Thanks for clarifying, Ivan. If we added the loader to the review page (we just see the review page header and the content of the review page is just a loader), that should take care of seeing the old data in the review page coming from data entry, right? Because the user will just see a loader w/ the review page header for a few moments until datapoints endpoint returns (at which point they'll see the rest of the page). I'll play around with this after I make endpoint adjustments and move some logic around! No need to worry about it in this PR!

2023-03-27 19:25 UTC, mxosman commented on publisher/src/components/Reports/DataEntryReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
Ivan brought up a really good point about the `metrics` data structure having a `datapoints` property that's almost always set to `null`. I can't remember if that was an intentional decision to deprecate this property in favor of calling the `/datapoints` endpoint or because it was too expensive or not - but, I wonder if it would be helpful now to include datapoints for each report?

<img width="273" alt="Screenshot 2023-03-27 at 2 20 40 PM" src="https://user-images.githubusercontent.com/59492998/228044838-fb1a8e23-acda-4f78-a1a1-915e44c5c5db.png">

2023-03-28 01:26 UTC, lilidworkin commented on publisher/src/components/Reports/ReviewReportDataEntry.tsx
> -      <PublishConfirmationSummaryPanel reportID={reportID} />
Oops, thanks!

2023-03-28 01:42 UTC, lilidworkin commented on publisher/src/components/Reports/DataEntryReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
Interesting, thanks so much for calling this out, @ivan-kishko and @mxosman ! A few thoughts (really just for @mxosman  -- @ivan-kishko can ignore this for now):

* I don't remember the story behind this property -- can you investigate a bit on the backend and see what you can figure out? The way I'd do that is do a search for `"datapoints"` -- _include_ the quotation marks, because we're looking for backend code that looks something like 'return {"metrics": [{"datapoints": <some json> ...}, ...]`. Then, see if you can trace upwards to see when this property is populated and when it isn't. I believe this is something Terry did, so we're going to have to reverse engineer it because we can't ask him :(
* It's definitely not a bad idea to start using this property now! However, there are a few things to consider: 1) how expensive it is, and 2) when do we _actually_ need the datapoints. We only need the datapoints when we load the Review page, which only happens when the user is publishing a Record. Most of the time the user loads the Records page or an individual Record, they are not going to be publishing. So unless it's very cheap to add the datapoints to the response in all cases, we probably don't want to. Thus, my intuition is that we shouldn't add them in all cases, but we _should_ add them to your `get_reports_by_id` endpoint, which we call when the user hits publish. LMK if that makes sense!
* It probably won't be straightforward how to populate the `datapoints` property. When you get to this point in the project, it would be good to write up a few sentences explaining what you need to do, and then start a thread with me and @nichelle-hall to discuss the best approach!

Generally this is a little confusing -- we have two different data models -- Metrics (each metric has multiple datapoints) and Datapoints. Most of our frontend pages work with the Metrics data model, but a few pages deal with Datapoints -- I think just the Data page and the Review page. This isn't ideal and I'm not 100% sure why this is the case, but it is probably out of scope for now to refactor.

2023-03-28 01:47 UTC, lilidworkin commented on publisher/src/components/Reports/BulkActionReview.tsx
> +            key: metric.key,
I agree @mxosman ! And I'm actually pretty sure that the metric will only show up in this side panel if there is _some_ data provided. Is that right @ivan-kishko ? If so, then for now, @ivan-kishko can you actually just change the logic as follows:

* Review page after Data Entry Page: keep logic as currently implemented for empty check mark vs. red error vs. empty checkbox 
* Review page after Bulk Publish: always show blue checkmark
* Review page after Bulk Upload: always show blue checkmark

Thank you!

2023-03-28 01:50 UTC, lilidworkin approved these changes
Thank you @ivan-kishko ! Here are my thoughts on the remaining discussion items:

* Loading page: You can leave this as-is for now -- @mxosman can explore alternatives when he works on this later!
* Datapoints response: @mxosman will take it from here!
* Empty checkmarks: This is the only remaining TODO for you -- just change the logic to be always a blue checkmark (unless you're coming from Data Entry, in which case keep the logic as is).

After you address the last bullet point, you can go ahead and merge! I cleared out Humprey's old review so you should be unblocked.

2023-03-28 10:57 UTC, merged

2023-03-28 16:03 UTC, mxosman commented on publisher/src/components/Reports/DataEntryReview.tsx
> +      await datapointsStore.getDatapoints(agencyId);
* Will do! Thank you for the strategy!
* That makes perfect sense! I agree - definitely not needed in all cases. I'll add the datapoints just for the reports returned by `get_reports_by_id` endpoint.
* Sounds great! Will do!

Agreed on the two different data models being confusing. You're right that it's only the data viz and review page that deal with datapoints - I'm wondering if it's just an ready-to-go transformed data structure that allows the FE to easily render them & filter them in a visual/table format? I feel like it might've been inspired by what Recharts needed -- but, I can't recall. Happy to revisit this if we ever want to explore consolidation/refactor -- it might be a matter of having the FE handle all of the data transformation - but would want to dig deeper into what inspired the separate endpoint and data structure.