[Bulk Upload] Adjust title / definition of a successfully saved metric
Recidiviz/justice-counts pull request #516
Opened 2023-03-21 21:51 UTC by morden35

## Description of the change

> Description here

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Related to [#19584](https://github.com/Recidiviz/recidiviz-data/issues/19584)

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-03-21 21:53 UTC, morden35 commented on publisher/src/components/DataUpload/DataUpload.tsx
> -import { useStore } from "../../stores";
My VSCode is automatically rearranging the order of imports, which is causing a warning when the app is run

2023-03-21 21:57 UTC, morden35 commented
This is my first pass at frontend/react in a long time! I know this PR will need a ton of work. Please don't hold back on any feedback or suggestions! Thank you!

2023-03-21 22:40 UTC, mxosman commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.datapoints.length > 0;
Just to clarify - we are using the presence of `datapoints` to determine whether or not a metric is successful (if there are any, it is successful, if there are none - unsuccessful) and no longer the `metric_errors` property, right? If so, this looks great to me! You can delete all the commented out code too.

2023-03-21 22:44 UTC, mxosman commented on publisher/src/components/DataUpload/DataUpload.tsx
> -import { useStore } from "../../stores";
Ah - yes. There is a line in the settings.json of VS code that was in the backend setup that organized imports in a different way on the FE after saving the file - took me a while to figure out what was going on! LMK if you want to disable it unless it is working fine for you in the BE!

One thing you can do after you've finished your edits in the file and save it is run `yarn lint --fix` and it will reorganize the import. Then, I would commit and push. LMK if that doesn't work!

Running `yarn lint` will tell you any other linting errors/warnings, but I think the imports is the only thing here!

2023-03-22 14:35 UTC, lilidworkin reviewed
Cool, nice work diving into the frontend!

As per our convo yesterday though, I think we decided we didn't want to outright error if there are missing metrics, right? So instead of "We encountered 12 errors" can it be like "0 metrics were saved successfully"?

2023-03-22 14:35 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.datapoints.length > 0;
I think we probably _also_ want to make sure that there are no errors, in addition to there being datapoints, right @morden35 ?

2023-03-22 16:06 UTC, morden35 commented on publisher/src/components/DataUpload/DataUpload.tsx
> -import { useStore } from "../../stores";
oh fantastic! Thank you! this did the trick

2023-03-22 16:09 UTC, morden35 commented
> Cool, nice work diving into the frontend!
> 
> As per our convo yesterday though, I think we decided we didn't want to outright error if there are missing metrics, right? So instead of "We encountered 12 errors" can it be like "0 metrics were saved successfully"?

Good point! I wasn't focusing on the error message at this point (I figured that would be a separate pr). Although I see that this logic is all interconnected. I will try to take a more holistic approach at this today

2023-03-22 17:49 UTC, morden35 commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.datapoints.length > 0;
hmm I need to think about this more. metric.metric_errors will contain both errors and warnings. in the presence of warnings, data may or may not be saved. in the presence of errors, data will not be saved (i think)

2023-03-22 19:25 UTC, morden35 commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
this will be true if len(metric_key_to_successfully_ingested_sheet_names[metric_definition.key]) > 0 see https://github.com/Recidiviz/recidiviz-data/pull/19684/files#diff-d3e180104898a32d7cc8f2a707469df2f23b7c2350b5e6d1946e72c173194ee4R342

2023-03-22 21:17 UTC, mxosman commented on publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
> +        {/* Case 2: More than 1 metric was saved */}
tiniest nit: instead of "More than 1" - something like "1 or more" since it'll show for just one metric saved.

2023-03-22 21:25 UTC, mxosman approved these changes
FE looks great to me, Michelle! Happy to approve but not sure if @lilidworkin wants to give another pass!

2023-03-22 21:40 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
I guess I'm curious if we need this -- why can't the logic be:

`const isSuccessfulMetric = (metric.metric_errors.length === 0 || noSheetErrorsFound) && metric.datapoints.length > 0`

If there are problems with that, just lmk!

2023-03-22 21:41 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
Basically, this is the same as the logic we currently have, but _also_ requires the metric to have datapoints present (i.e. not be missing)

2023-03-22 21:43 UTC, lilidworkin commented on publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
> +            <BlueText>{successfulMetricsCount}</BlueText> metrics were saved
Since we know successfulMetricsCount === 0 here, maybe we just say "No metrics were saved successfully."?

2023-03-22 21:44 UTC, lilidworkin commented on publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
> +        {/* Section 1: Show number of metrics successfully ingested */}
I like how you broke this into "sections", great idea!

2023-03-22 21:44 UTC, lilidworkin commented on publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
>              We encountered <RedText>{errorCount}</RedText> error
So this is still counting/showing Missing Metrics as errors. As per our convo yesterday, I think we decided not to do that? Or are you planning to do that in a separate PR? Totally fine if so!

2023-03-22 21:46 UTC, lilidworkin requested changes
Left some comments/questions that we should resolve before merging, but really excited to see you so productive on the frontend already @morden35 ! Great work!

2023-03-22 21:49 UTC, morden35 commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
so perhaps one solution is to do
`const isSuccessfulMetric = (noSheetErrorsFound && metric.datapoints.length > 0)`

so we're just concerned with errors (not warnings) and if data has been saved

2023-03-22 21:49 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
Ah I see, interesting. Is that why we have the `|| no sheetErrorsFound` logic, though? Basically it seems the logic is "either there are no errors at all, OR there are but there are none with type ERROR". Curious if @mxosman remembers the reasoning here.

2023-03-22 21:50 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
Ah yea I think we just posted at the same time -- I agree! -- I think the `metric.metric_errors.length === 0` part is redundant, and will always be "trumped" by the second part of that or statement. I think `const isSuccessfulMetric = (noSheetErrorsFound && metric.datapoints.length > 0)` is right.

2023-03-22 22:03 UTC, mxosman commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
> Ah I see, interesting. Is that why we have the `|| no sheetErrorsFound` logic, though? Basically it seems the logic is "either there are no errors at all, OR there are but there are none with type ERROR". Curious if @mxosman remembers the reasoning here.

Blast from the past! Hard to fully remember - but I think when I wrote this originally, it was checking to see if the `metric.metric_errors` array was empty or if not empty, check in each sheet to see if there were any errors or just warnings (because I believe at the time the `metric.metric_errors` array held both errors and warnings within the sheets and there was a possibility of the `metric.metric_errors` array's length being > 1 and only have all warnings within the sheets).

2023-03-23 11:59 UTC, lilidworkin commented on publisher/src/components/DataUpload/DataUpload.tsx
> +        const isSuccessfulMetric = metric.successful_ingest;
Thanks @mxosman ! Just to clarify, I think our confusion (but @morden35 correct me if I'm wrong) is that this statement is doing the following:
1. Checking that the length of metric.metric_errors is 0, OR
2. Checking that metric.metric_errors doesn't contain any true errors

Is it true that the logic/behavior would be the same if we only did check 2, and not check 1? Because there are no cases where 1 is true but 2 is false, right? So the only possibility is that 1 is false and 2 is true, or both are true/false, in which cases it should be sufficient just to look at 2?

Sorry if this is a convoluted/confusing question, haha! I think we're all in agreement in any case.

2023-03-23 15:41 UTC, morden35 commented on publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
>              We encountered <RedText>{errorCount}</RedText> error
planning to do this in a separate pr!

2023-03-24 12:59 UTC, lilidworkin approved these changes
Looks perfect @morden35 , thanks for making these changes and sorry for the back-and-forth! Thanks @mxosman  for sanity checking us!

2023-03-24 15:11 UTC, merged

2023-03-24 19:48 UTC, mxosman commented
🥳 🥳 🥳 Beautifully done, Michelle!