Metric Availability page
Recidiviz/justice-counts pull request #575
Opened 2023-04-17 12:26 UTC by ivan-kishko

## Description of the change

> Metric settings availability page implementation

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #562 (Partly)

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-04-18 17:51 UTC, hobuobi requested changes
Awesome work! A few things to address before merging: 

- Race & Ethnicity should still use the form and display the selections in a grid (this was an omission in the designs, our bad!). I've included designs in the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7939-17453&t=HNHfbUGMMiXxE6wz-0); basically: 
    - The grid and call to action box should appear inline, alongside all the other Breakdown sections. 
    - The call to action box should open up a modal containing the Race & Ethnicity Form. 
- The (i) icons should show a tooltip on hover. The contents for this are in the [Figma.](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7700-21855&t=HNHfbUGMMiXxE6wz-0) 
- We still need to implement a "Back to All Metrics" link – using the Sector name is not very discoverable. I have suggested something in the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7942-18236&t=HNHfbUGMMiXxE6wz-0), which Kristen should probably validate or refine.

More aesthetic adjustments (Kristen should validate, but go ahead and implement for now): 
- Hover state for the breakdown categories should be a light gray (rgba(0, 115, 229, 0.05)). 
    -  We should use the same hover color for the overview page metrics/rows. 
- The breakdown pills ("Staff Types (3/7)") should turn slightly darker on hover (rgba(0, 115, 229, 0.2)? 
- Long metric names are taking up a lot of space. Can we set some kind of rule such that if the metric name is longer than X (20?) characters, we reduce the font size (3rem)? 
- Anywhere there's a blue link ("Select All") or pill ("Staff Types (3/7)"), the hover state should be #0056E0. 
- The subpages ("Define metrics," "Set metric availability") should be gray when unselected and darker gray on hover (similar to what we do on the previous page). 
- The (2) next to Define Metrics should also be gray, rather than black.

2023-04-18 22:01 UTC, mxosman reviewed
Wow, Ivan - beautifully implemented! Huge kudos to design as well because this page feels **_so_** much less overwhelming and is becoming such a lovely experience.

There are a couple of thoughts I have that are more design related (not at all blocking this amazing progress):
* For metrics without breakdowns - can we remove the entire breakdown section?
  * <img width="328" alt="Screenshot 2023-04-18 at 4 35 55 PM" src="https://user-images.githubusercontent.com/59492998/232913377-b422b5ff-7dd3-4358-9bba-80a6e709bfcb.png">

* The breakdown headers feel a bit hard to see and in terms of font size and top+bottom padding - especially when there are multiple breakdowns. Not sure if spacing alone can solve this or if it would require both spacing and font size increases.
  * <img width="328" alt="Screenshot 2023-04-18 at 4 39 20 PM" src="https://user-images.githubusercontent.com/59492998/232913891-d3094c10-386a-4f4b-9ba7-cca418bd4e3a.png">
* +1 to the back to metric overview page arrow or something - clicking on the system name was not intuitive to me.

2023-04-19 10:13 UTC, ivan-kishko commented on publisher/src/components/MetricSettings/MetricAvailability.tsx
> +import * as Styled from "./MetricAvailability.styled";
Well, when I was doing something about data entry I was confused when I saw a component TextField and thought it was styled one but it was React one) So when refactor tasks were created I decided that this is a good moment to implement some changes in code style so styled components are not confused with React components, also as a bonus it is only 1line import instead of tower of imported components) Something like that

2023-04-19 10:14 UTC, ivan-kishko commented on common/components/RadioButton/RadioButton.tsx
> +}
It will be a foundation for Radio button shared component when I get to this refactor task

2023-04-19 10:35 UTC, ivan-kishko commented
> Wow, Ivan - beautifully implemented! Huge kudos to design as well because this page feels **_so_** much less overwhelming and is becoming such a lovely experience.
> 
> There are a couple of thoughts I have that are more design related (not at all blocking this amazing progress):
> 
> * For metrics without breakdowns - can we remove the entire breakdown section?
>   
>   * <img alt="Screenshot 2023-04-18 at 4 35 55 PM" width="328" src="https://user-images.githubusercontent.com/59492998/232913377-b422b5ff-7dd3-4358-9bba-80a6e709bfcb.png">
> * The breakdown headers feel a bit hard to see and in terms of font size and top+bottom padding - especially when there are multiple breakdowns. Not sure if spacing alone can solve this or if it would require both spacing and font size increases.
>   
>   * <img alt="Screenshot 2023-04-18 at 4 39 20 PM" width="328" src="https://user-images.githubusercontent.com/59492998/232913891-d3094c10-386a-4f4b-9ba7-cca418bd4e3a.png">
> * +1 to the back to metric overview page arrow or something - clicking on the system name was not intuitive to me.

[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561) - Check this out (P.S. will do back to overview in next commit)

2023-04-19 10:35 UTC, ivan-kishko commented on common/components/RadioButton/index.ts
> +// export * from "./types";
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:35 UTC, ivan-kishko commented on common/components/RadioButton/types.ts
> +// =============================================================================
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:35 UTC, ivan-kishko commented on common/components/RadioButton/RadioButton.styled.tsx
> +  width: ${({ fullWidth }) => fullWidth && "100%"}
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:35 UTC, ivan-kishko commented on common/components/RadioButton/RadioButton.styled.tsx
> +  ${({ fullWidth }) => fullWidth && "width: 100%"}
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:36 UTC, ivan-kishko commented on common/components/RadioButton/RadioButton.tsx
> +interface Props extends InputHTMLAttributes<HTMLInputElement> {
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:36 UTC, ivan-kishko commented on publisher/src/components/MetricSettings/MetricAvailability.styled.tsx
> +  ${({ disabled }) => disabled && `pointer-events: none; opacity: 0.5`}
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 10:36 UTC, ivan-kishko commented on publisher/src/components/MetricSettings/MetricAvailability.tsx
> +                    Select All
[d0bc1b4](https://github.com/Recidiviz/justice-counts/pull/575/commits/d0bc1b4cf7ef52ae70c517c7a52abbe9335f4561)

2023-04-19 11:23 UTC, ivan-kishko commented
> Awesome work! A few things to address before merging:
> 
> * Race & Ethnicity should still use the form and display the selections in a grid (this was an omission in the designs, our bad!). I've included designs in the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7939-17453&t=HNHfbUGMMiXxE6wz-0); basically:
>   
>   * The grid and call to action box should appear inline, alongside all the other Breakdown sections.
>   * The call to action box should open up a modal containing the Race & Ethnicity Form.
> * The (i) icons should show a tooltip on hover. The contents for this are in the [Figma.](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7700-21855&t=HNHfbUGMMiXxE6wz-0)
> * We still need to implement a "Back to All Metrics" link – using the Sector name is not very discoverable. I have suggested something in the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=7942-18236&t=HNHfbUGMMiXxE6wz-0), which Kristen should probably validate or refine.
> 
> More aesthetic adjustments (Kristen should validate, but go ahead and implement for now):
> 
> * Hover state for the breakdown categories should be a light gray (rgba(0, 115, 229, 0.05)).
>   
>   * We should use the same hover color for the overview page metrics/rows.
> * The breakdown pills ("Staff Types (3/7)") should turn slightly darker on hover (rgba(0, 115, 229, 0.2)?
> * Long metric names are taking up a lot of space. Can we set some kind of rule such that if the metric name is longer than X (20?) characters, we reduce the font size (3rem)?
> * Anywhere there's a blue link ("Select All") or pill ("Staff Types (3/7)"), the hover state should be #0056E0.
> * The subpages ("Define metrics," "Set metric availability") should be gray when unselected and darker gray on hover (similar to what we do on the previous page).
> * The (2) next to Define Metrics should also be gray, rather than black.

[35a936f](https://github.com/Recidiviz/justice-counts/pull/575/commits/35a936fc4c2de0f2b87289d9567855b2c003dd02) (without race/ethnicities)

2023-04-19 15:40 UTC, mxosman commented on common/components/RadioButton/RadioButton.styled.tsx
> +  ${({ fullWidth }) => fullWidth && "width: 100%;"};
I think we have too many `;` now - the one at the end of the line should suffice, you can remove the one after the 100% and keep the one at the end.

2023-04-19 15:41 UTC, mxosman commented on publisher/src/components/MetricSettings/MetricAvailability.styled.tsx
> +  ${({ disabled }) => disabled && "pointer-events: none;"};
Same here - I think the `;` at the end should be enough

2023-04-19 15:41 UTC, mxosman commented on publisher/src/components/MetricSettings/MetricAvailability.styled.tsx
> +  ${({ disabled }) => disabled && "pointer-events: none; opacity: 0.5;"};
Same with the `;`

2023-04-19 15:47 UTC, mxosman commented on publisher/src/components/MetricSettings/MetricAvailability.tsx
> +import * as Styled from "./MetricAvailability.styled";
That makes so much sense - I love it - I've run into the same confusion at times. Thank you for explaining your thought process and for taking the initiative.

2023-04-19 15:49 UTC, mxosman commented on publisher/src/components/MetricSettings/MetricAvailability.tsx
> +                    Select All
Nice!! Thank you, Ivan!

2023-04-20 13:31 UTC, ivan-kishko commented on common/components/RadioButton/RadioButton.styled.tsx
> +  ${({ fullWidth }) => fullWidth && "width: 100%;"};
[670afc2](https://github.com/Recidiviz/justice-counts/pull/575/commits/670afc21a7c059c4415bfa6290e883a81c3f77dc)

2023-04-20 13:31 UTC, ivan-kishko commented on publisher/src/components/MetricSettings/MetricAvailability.styled.tsx
> +  ${({ disabled }) => disabled && "pointer-events: none;"};
[670afc2](https://github.com/Recidiviz/justice-counts/pull/575/commits/670afc21a7c059c4415bfa6290e883a81c3f77dc)

2023-04-20 13:32 UTC, ivan-kishko commented on publisher/src/components/MetricSettings/MetricAvailability.styled.tsx
> +  ${({ disabled }) => disabled && "pointer-events: none; opacity: 0.5;"};
[670afc2](https://github.com/Recidiviz/justice-counts/pull/575/commits/670afc21a7c059c4415bfa6290e883a81c3f77dc)

2023-04-20 16:35 UTC, mxosman commented
> @hobuobi @mxosman [4f92a68](https://github.com/Recidiviz/justice-counts/pull/575/commits/4f92a685d99296bc7006196e5bcbe9a385188949) - commit with race ethnicities modal.

Hi Ivan! A couple of quick things that stood out to me when I was playing around (still haven't reviewed everything yet):
* I think we should allow a user to click on the call out box for the Race/Ethnicities when everything is either disabled/null (hasn't been set by the user yet). Right now, the only way to access the form is by clicking on `Select All`
  * <img width="307" alt="Screenshot 2023-04-20 at 11 31 52 AM" src="https://user-images.githubusercontent.com/59492998/233430764-6aa27dd7-2b1d-4ced-9530-e9aa18535baf.png">
* I am not able to save any changes yet - here's a log of the issue:
  * <img width="428" alt="Screenshot 2023-04-20 at 11 30 14 AM" src="https://user-images.githubusercontent.com/59492998/233430855-25b1a162-5906-4360-ad3f-3b350679fafb.png">

2023-04-20 22:20 UTC, mxosman approved these changes
Latest commits LGTM! Thank you so much for all of the adjustments, Ivan!

2023-04-24 14:53 UTC, lilidworkin approved these changes
Just tested this out and it looks fantastic @ivan-kishko , thank you!

2023-04-24 15:54 UTC, merged