Standalone version of bulk upload review page
Recidiviz/justice-counts pull request #686
Opened 2023-05-31 13:10 UTC by ivan-kishko

## Description of the change

> Mock for standalone uploaded spreadsheet review page

## Type of change
Type: Feature

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #683 

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-06-02 13:42 UTC, lilidworkin reviewed
Looks great @ivan-kishko ! One request to do some code deduplication.

2023-06-02 13:42 UTC, lilidworkin commented on publisher/src/components/DataUpload/SpreadsheetReview.tsx
> +  // mock data that will be replaced with one from store
Nice!

2023-06-02 13:42 UTC, lilidworkin commented on publisher/src/components/DataUpload/SpreadsheetReview.tsx
> +  // here will be fetch spreadsheet call and loading and error handling
Awesome, thanks for writing this code even though the backend doesn't exist yet :)

2023-06-02 13:42 UTC, lilidworkin commented on publisher/src/components/DataUpload/SpreadsheetReview.tsx
> +  const existingReports = [...updatedReportIds, ...unchangedReportIds]
A lot of the code below is the exact same as in UploadReview. That isn't ideal because we may make changes in one version but forget to make the same change in the other. Is it possible to refactor this code into some shared utilities that can be used by both files?

2023-06-02 15:34 UTC, mxosman commented on publisher/src/components/DataUpload/SpreadsheetReview.tsx
> +  // here will be fetch spreadsheet call and loading and error handling
+1!

2023-06-06 13:45 UTC, ivan-kishko commented on publisher/src/components/DataUpload/SpreadsheetReview.tsx
> +  const existingReports = [...updatedReportIds, ...unchangedReportIds]
[531c86b](https://github.com/Recidiviz/justice-counts/pull/686/commits/531c86b0d618a7fa3f4d302e67ec34adc71473c5) maybe something like this should do the trick

2023-06-06 19:50 UTC, lilidworkin approved these changes
This looks fantastic @ivan-kishko , thank you for doing that deduplication, really appreciate it!

2023-06-06 21:38 UTC, mxosman requested changes
Just took a look at the new changes - I don't believe the latest UploadReview logic has been included here likely due to this branch starting before the latest UploadReview changes were merged.

Here's a reference to the latest commit in `main` - if there's a way to incorporate the latest changes with this PR that would be ideal - otherwise, things might break.

https://github.com/Recidiviz/justice-counts/commit/b886de06ce68a83d150b7265b0b3a3e3fab90304#diff-e37155ce4d71f2c1c1f4c87b21c7f4e943d9d87c4b066b7e13cf95961a96a4d0

2023-06-06 23:41 UTC, lilidworkin commented
Oooh great catch @mxosman !!

2023-06-07 10:47 UTC, ivan-kishko commented
> Just took a look at the new changes - I don't believe the latest UploadReview logic has been included here likely due to this branch starting before the latest UploadReview changes were merged.
> 
> Here's a reference to the latest commit in `main` - if there's a way to incorporate the latest changes with this PR that would be ideal - otherwise, things might break.
> 
> [b886de0#diff-e37155ce4d71f2c1c1f4c87b21c7f4e943d9d87c4b066b7e13cf95961a96a4d0](https://github.com/Recidiviz/justice-counts/commit/b886de06ce68a83d150b7265b0b3a3e3fab90304#diff-e37155ce4d71f2c1c1f4c87b21c7f4e943d9d87c4b066b7e13cf95961a96a4d0)

[0b1eec8](https://github.com/Recidiviz/justice-counts/pull/686/commits/0b1eec880c207db6ce26318dee4dd6bc1c23ef95) I guess this is now up to date, but looks like CSVs are not valid again so I cannot like test it properly, and dont have filled mock data now because of that as well

2023-06-07 14:04 UTC, lilidworkin commented
@ivan-kishko can you clarify "but looks like CSVs are not valid again so I cannot like test it properly, and dont have filled mock data now because of that as well" -- what do you mean that the CSVs are not valid again? cc @mxosman to help with this (thank you!)

2023-06-07 17:19 UTC, ivan-kishko commented
> @ivan-kishko can you clarify "but looks like CSVs are not valid again so I cannot like test it properly, and dont have filled mock data now because of that as well" -- what do you mean that the CSVs are not valid again? cc @mxosman to help with this (thank you!)

I mean those csvs you gave me few days ago are like empty again for me, maybe it has smth to do with new logic and data types

2023-06-07 17:30 UTC, lilidworkin commented
@ivan-kishko you mean they are empty when you upload them? can you take a video or screenshots? Can you also upload the files here so @mxosman can test it out too? I forget which ones I sent you. Thank you!

2023-06-07 18:41 UTC, ivan-kishko commented
> @ivan-kishko you mean they are empty when you upload them? can you take a video or screenshots? Can you also upload the files here so @mxosman can test it out too? I forget which ones I sent you. Thank you!

I mean they are full of errors and as a result nothing to review 
[JAILS_success.xlsx](https://github.com/Recidiviz/justice-counts/files/11680883/JAILS_success.xlsx)

2023-06-07 19:59 UTC, mxosman commented
> [0b1eec8](https://github.com/Recidiviz/justice-counts/pull/686/commits/0b1eec880c207db6ce26318dee4dd6bc1c23ef95) I guess this is now up to date, but looks like CSVs are not valid again so I cannot like test it properly, and dont have filled mock data now because of that as well

> > @ivan-kishko you mean they are empty when you upload them? can you take a video or screenshots? Can you also upload the files here so @mxosman can test it out too? I forget which ones I sent you. Thank you!
> 
> I mean they are full of errors and as a result nothing to review [JAILS_success.xlsx](https://github.com/Recidiviz/justice-counts/files/11680883/JAILS_success.xlsx)

Thanks, Ivan & Lili! I just tested the JAILS_success.xlsx you attached and uploaded in the Jails agency locally and it uploaded fine for me with 11 saved metrics. LMK how I can help debug! When you say 'CSVs' are you just referring the spreadsheet you attached or an actual `.csv` file? If the latter - would you mind sharing the .csv you're using and I'll try it on my end.

Also tested the new super agency upload functionality works perfectly fine - thank you!

2023-06-07 20:01 UTC, mxosman approved these changes
LGTM! Let me know how I can help with the CSV/mock data issue you're seeing on your end!

2023-06-07 20:01 UTC, lilidworkin commented
Thanks for testing @mxosman ! Phew, glad it's working for you. Can you try running against staging backend since that's what Ivan is doing? Maybe there's just a mismatch between main and staging that's causing his problem ...

2023-06-07 20:01 UTC, mxosman commented
> Thanks for testing @mxosman ! Phew, glad it's working for you. Can you try running against staging backend since that's what Ivan is doing? Maybe there's just a mismatch between main and staging that's causing his problem ...

Great idea! Will do!

2023-06-07 20:23 UTC, lilidworkin commented
Weird! @ivan-kishko can you upload a video?

2023-06-08 10:04 UTC, merged