[21327] add tracking functions based on design doc
Recidiviz/justice-counts pull request #704
Opened 2023-06-07 22:07 UTC by alfonsogoberjr

## Description of the change

Adds tracking functions according to the questions posed [here](https://paper.dropbox.com/doc/Design-Doc-Internal-Dashboard--B5z6zfCM19i6PAV6KGrDfwnrAg-R22hiIqWxF0SJvvQ8kojf)

## Related issues

Closes #21327

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2023-06-08 15:31 UTC, lilidworkin reviewed
Excited to see this getting started!

2023-06-08 15:31 UTC, lilidworkin commented on publisher/src/analytics.ts
> +  track("publisher_login", {
I'm wondering how this will interact with the `identify` call we make [here](https://github.com/Recidiviz/justice-counts/blob/bbd9a2d6918e0317cda7c64e6d6ac064397c9245/publisher/src/components/Auth/AuthStore.ts#L101). My understanding is that this also gets called after the user logs in. Or actually maybe it gets called every time you load the page, I'm not sure. Anyway, would be good to figure out if we need both, and in what order they're going to be called.

I guess that also raises another question -- what do we actually mean by "login" -- do we mean you filled out your username/email on the Auth0 modal? What if you login, close your window, and then re-open Publisher -- you'll probably still be logged in -- but do we want to treat that as a separate login? I'm not sure it matters too much and I don't have strong feelings either way, we should just make sure we're clear on the behavior and document it somewhere. (Might be good to get a doc started with a list of the events we're tracking as well as a pointer in the code to where they're tracked?)

2023-06-08 15:31 UTC, lilidworkin commented on publisher/src/analytics.ts
> +  track("publisher_login", {
Oh also -- super nit, but I'm not sure we need the "publisher_" prefix on these events? Since they're all being logged from the Publisher app?

2023-06-08 15:31 UTC, lilidworkin commented on publisher/src/analytics.ts
> +  track("publisher_metric_configured", {
As per earlier conversations -- do we need to also include other information in this event, like the total number of metrics configured so far? Otherwise in order to get that information, will we need to do a sum across events of this type? Which might be fine -- just wanted to confirm/clarify.

2023-06-08 15:31 UTC, lilidworkin commented on publisher/src/analytics.ts
> +export const trackMetricEnabled = ({
Now that I think about it, we might be able to get away with just the trackMetricConfigured event, and include a boolean flag for enabled/disabled. Since configuring a metric means (for our purposes here -- in reality it's a little more complicated) either enabling or disabling it (the default state is null, neither enabled nor disabled). So when they enable, we send a configured event with enabled = True, and when they disable, we send a configured event with enabled = False.

Later we'll have to figure out if / how we also want to track enabling/disabling of diaggregations and dimensions. I think we can punt on that for now, but it might be good to chat with @mxosman to get a better understanding of how that part of the flow works.

2023-06-09 15:11 UTC, lilidworkin commented
@alfonsogoberjr quick thing to note, not for this PR -- I know we already have tracking events for creating and publishing reports, but I don't think those events are currently getting called in all the right places (since the code has changed a lot since this was initially written and we've shipped new ways to create reports, like bulk upload, and new ways to publish reports, like bulk publishing). Just something to be aware of -- both @mxosman and I can help identify where the updates need to be made.

2023-06-09 16:03 UTC, mxosman commented
This is super exciting, Alfonso! I'm looking forward to seeing these specific trends - happy to help in anyway!

2023-06-12 14:49 UTC, lilidworkin requested changes
Thanks @alfonsogoberjr ! I think this is heading in the right direction, but I think there are some issues with the logic. Relatedly, I like to ask all engineers to include a "test plan" of some sort to their PR descriptions -- that can either be something like "I added unit tests" or "here's a screenshot/video of how it looks now" or "here are some console.logs that prove that it works." Could you add more detail to your PR description explaining exactly when you expect each of these events to be called, and then show some proof that they were actually called then? There's a TEST_SENDING_ANALYTICS flag that you can set that will log to the console when the event would have actually gotten sent to Segment, which might help!

cc @mxosman who should definitely review this PR as well!

2023-06-12 14:49 UTC, lilidworkin commented on publisher/src/analytics.ts
> +  track("publisher_login", {
@alfonsogoberjr any thoughts on my other comments above? 

1) When will we call `trackLogin` and how is this the same/different from `identify`?
2) Should we call this when the user fills out username/password or when they start a new session?
3) Do we need the `publisher_` prefix?

Curious if @mxosman has thoughts too!

2023-06-12 14:49 UTC, lilidworkin commented on publisher/src/analytics.ts
> +export const trackMetricEnabled = ({
@alfonsogoberjr any thoughts on whether it's better/worse to have a single `trackMetricConfiguration` event with an enabled/disabled flag, or to keep these as three separate events?

2023-06-12 14:49 UTC, lilidworkin commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
I'm still not sure I understand how we'll be able to use these events to determine how many metrics have been configured overall. Does the `updatedMetricSettings` include that information, or does it just include information about this individual metric?

2023-06-12 14:49 UTC, lilidworkin commented on publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> +      if (enabledStatus)
It looks like `handleUpdateMetricEnabledStatus` gets called when the user clicks the "Not Available" button (i.e. turning a metric off) but that `handleUpdateMetricReportFrequency` gets called when a user clicks the "Monthly" or "Annual" button (i.e. turning a metric on). I don't think `handleUpdateMetricEnabledStatus` ever gets called with `true`? If so we'll need to adjust this and call `trackMetricEnabled` from `handleUpdateMetricReportFrequency`  instead.

2023-06-12 14:49 UTC, lilidworkin commented on publisher/src/stores/MetricConfigStore.tsx
> +    trackMetricConfiguration({ agencyId, updatedMetricSettings });
So this is going to get called every time a user makes _any_ change to the metric configuration page -- is that what we want? I thought maybe we just wanted to call this when a user configures their metric (i.e. turns it on or off) for the very first time?

2023-06-13 12:55 UTC, lilidworkin reviewed
@alfonsogoberjr another quick thought about this PR:

I realized the scope/intention is a little unclear to me -- is this meant to be the first PR in a series (i.e. this one just adds tracking functions to analytics.js, but another one actually starts calling those functions in all the right places?) or is it meant to be comprehensive, i.e. all the changes we need to make in order to support the dashboard?

Two things might be helpful here:
1) Adding a more descriptive summary in the PR description to clarify the goal (generally we try to add as much context in the description as possible, though I'm certainly guilty of dropping the ball on this, haha)
2) Making a list of all the P0 items from the design doc, and annotating them with the Segment event we'll use to calculate it. This will help us see if we have full coverage, and if each event contains the right information.

2023-06-13 18:25 UTC, alfonsogoberjr commented on publisher/src/analytics.ts
> +export const trackMetricEnabled = ({
Agreed, I realize now the `enabled` field exists on the MetricSettings object

2023-06-13 18:30 UTC, alfonsogoberjr commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
I've been thinking about it - since a purely Segment-based accounting isn't going to work, we need some kind of metadata schema stored in our DB instead of ad-hoc requests across multiple data sources. So this PR wouldn't contain that just yet, until the outcome of our meeting is decided.

2023-06-13 18:56 UTC, lilidworkin commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
Ok cool makes sense!

2023-06-14 15:20 UTC, mxosman commented on publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> +      if (enabledStatus)
Great catch, Lili! You're right that `handleUpdateMetricEnabledStatus` only gets called when the `enabled` status is false. It's not immediately intuitive and I'm sure we can probably improve how we're naming things - but the selection options for a metric configuration are: 
* Not Available (which uses the `handleUpdateMetricEnabledStatus` function) 
* Monthly (which used the `handleUpdateMetricReportFrequency` function)
* Annual (which used the `handleUpdateMetricReportFrequency` function)

I think a better candidate for this would be the `saveMetricSettings` method in the `MetricConfigStore` which is called by both handler functions above.

2023-06-14 15:24 UTC, mxosman commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
If we're still pursuing segment and these tracking functions -- since the `MetricSettings` object can be verbose, I'm wondering if it would simplify things to just extract the `key` and `enabled` properties and use those two to track metric configuration here?

2023-06-14 15:26 UTC, lilidworkin commented on publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> +      if (enabledStatus)
@mxosman if we call it in `saveMetricSettings` though, won't it get called whenever metric config is updated, not just when metrics are enabled/disabled?

2023-06-14 15:36 UTC, mxosman commented on publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> +      if (enabledStatus)
That's a good point - though there aren't any other good centralized candidates I can think of to place this - aside from adding the tracking function in each of the above handler functions. If we wanted to put it in a central area like `saveMetricSettings` we could add conditionals to make sure it only runs if/when the enabled property is present in the `updatedMetricSettings` object.

2023-06-15 12:38 UTC, lilidworkin requested changes
@alfonsogoberjr , in [this comment](https://github.com/Recidiviz/justice-counts/pull/704#pullrequestreview-1475109244) I asked if you could add a test plan of some sort to your PR, and in [this comment](https://github.com/Recidiviz/justice-counts/pull/704#pullrequestreview-1477105756) I asked if you could make your PR description more detailed in general about the goal/scope of the PR. Thank you!

2023-06-15 12:38 UTC, lilidworkin commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
@alfonsogoberjr any thoughts on @mxosman 's comment above?

2023-06-15 16:41 UTC, alfonsogoberjr commented on publisher/src/analytics.ts
> +    updatedMetricSettings,
Sorry I missed this comment - that sounds great! I'll update

2023-06-15 16:49 UTC, alfonsogoberjr commented on publisher/package.json
> +    "@storybook/testing-library": "^0.1.0",
Linter wouldnt pass without it, for some reason

2023-06-15 16:50 UTC, alfonsogoberjr commented on publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> +      if (enabledStatus)
Hey I missed these comments with all of the other feedback going around. This makes sense.

2023-06-15 16:52 UTC, alfonsogoberjr commented on publisher/src/components/Reports/CreateReport.tsx
> +/* eslint-disable import/no-extraneous-dependencies */
weird, fixing

2023-06-15 17:03 UTC, alfonsogoberjr commented on publisher/package.json
> +    "@storybook/testing-library": "^0.1.0",
reset branch from main, something must have come over from the storybook branch

2023-06-15 17:07 UTC, closed without merging

2023-06-15 17:15 UTC, alfonsogoberjr commented
closed this because of too many concurrent discussions. All requested changes were implemented in new PR [here](https://github.com/Recidiviz/justice-counts/pull/713). There should be no storybook code now