[#771][Agency Dashboard] Only allowlisted agencies should have a dashboard (all others 404)
Recidiviz/justice-counts pull request #795
Opened 2023-07-28 21:17 UTC by alfonsogoberjr

## Description of the change

Adds an allowlist for the DashboardView

## Type of change

Type: Feature

## Related issues

Closes #771

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2023-07-28 22:07 UTC, mxosman approved these changes
Nice! LGTM!

2023-07-28 22:07 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      navigate("/404");
Should we move this outside of the useEffect? In my head, the order will go: fully render DashboardView component -> then run this useEffect. If we have this in the component-level scope, we can probably short circuit here and unmount.

2023-07-31 15:05 UTC, lilidworkin requested changes

2023-07-31 15:05 UTC, lilidworkin commented on agency-dashboard/src/utils/allowlist.ts
> +  ALLOW_LIST.includes(name);
Does it make more sense to have allowlist be a set, so that this is O(1) lookup rather than O(n)?

2023-07-31 15:05 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
Let's only run the allowlist if we are in production. When running locally or in staging, I think we want to be able to see every agency.

2023-07-31 15:05 UTC, lilidworkin commented on agency-dashboard/src/utils/allowlist.ts
> +export const ALLOW_LIST = [
So there's been a slight change of plans, for CLA we're actually going to allowlist just a single demo agency. We still need to set up this demo agency though (see my comment [here](https://recidiviz.slack.com/archives/C05FKU8LMPH/p1690815870480069)) so we can keep this for now, but I'll ask you to change it later!

2023-07-31 16:58 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
Got it

2023-07-31 21:30 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/allowlist.ts
> +  ALLOW_LIST.includes(name);
Yes good point

2023-07-31 21:30 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      navigate("/404");
working on it

2023-07-31 21:35 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
I think @mxosman or @morden35 could give you a pointer to how to determine if we are in prod or staging if that would be helpful!

2023-07-31 21:54 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      navigate("/404");
I could be totally wrong (just my current intuition) - not a high priority either!

2023-07-31 21:59 UTC, morden35 commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
Yeah! In the past I've used [api.environment](https://github.com/Recidiviz/justice-counts/blob/main/publisher/src/stores/API.ts#L38)

example [here](https://github.com/Recidiviz/justice-counts/blob/main/publisher/src/components/Header/hooks.tsx#L36)

2023-07-31 22:03 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
Absolutely! Here's where we do it in Publisher in the API helper store  (sending a GET request to `/api/init` will return an obj w/ an `env` property):

https://github.com/Recidiviz/justice-counts/blob/79b7277ef3aa4f1006b0467b0be5f42e3934b5fa/publisher/src/stores/API.ts#L31-L71

Agency Dashboards doesn't have this API store (I recall Terry wanting to try something different at the time using just a util function - (agency-dashboard/src/utils/networking.ts)[https://github.com/Recidiviz/justice-counts/blob/main/agency-dashboard/src/utils/networking.ts]) but

2023-07-31 22:03 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (agencyDataStore?.agency && !isAllowListed(agencyDataStore.agency))
Oh oops - just saw your response - thanks, Michelle!

2023-08-02 03:57 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      navigate("/404");
good point

2023-08-02 03:58 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      navigate("/404");
Ah no we can't actually, because the dependencies it uses to determine the values are temporarily undefined for the first few renders. So it will lead to a false-positive and 404 when it shouldn't

2023-08-02 03:59 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/allowlist.ts
> +  ALLOW_LIST.includes(name);
Yes

2023-08-02 04:15 UTC, merged

2023-08-02 13:33 UTC, lilidworkin commented on 1
> +Allowlist
@alfonsogoberjr I don't think this was supposed to be committed!

2023-08-02 13:33 UTC, lilidworkin commented on agency-dashboard/src/utils/env.ts
> +export const getEnv = () => {
Nice, great helper function!

2023-08-02 15:39 UTC, mxosman commented on agency-dashboard/src/utils/env.ts
> +export const getEnv = () => {
Ah - nice! No need for an API call - just getting it from the URL - great solution!!

2023-08-02 15:40 UTC, lilidworkin commented on agency-dashboard/src/utils/env.ts
> +export const getEnv = () => {
Oh I didn't even notice that. Yea I think that's ok! It's not robust to URL changes but I think that's fine, I don't think we'll be changing our URLs any time soon haha.

2023-08-02 15:43 UTC, lilidworkin commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/publisher-staging.justice-counts.org/i",
Omg yes, great catch

2023-08-02 15:44 UTC, lilidworkin commented
@alfonsogoberjr just for the future, when a reviewer requests changes, it's best practice to re-request review from them before merging

2023-08-02 20:59 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/publisher-staging.justice-counts.org/i",
Ah yes

2023-08-02 23:30 UTC, alfonsogoberjr commented
> @alfonsogoberjr just for the future, when a reviewer requests changes, it's best practice to re-request review from them before merging

Yeah sorry about that, there was already an approval and I thought I had addressed everything