[#771][Agency Dashboard] Only allowlisted agencies should have a dashboard (all others 404)
Recidiviz/justice-counts pull request #809
Opened 2023-08-02 21:13 UTC by alfonsogoberjr

## Description of the change

Adds corrections and feedback from previous PR 

Closes #771

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2023-08-02 21:25 UTC, lilidworkin requested changes
Can we delete this rogue file as per my comment [here](https://github.com/Recidiviz/justice-counts/pull/795/files#r1281913615)?

2023-08-02 21:25 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (
Why is this block duplicated?

2023-08-02 21:25 UTC, lilidworkin commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/dashboard-staging.justice-counts.org/i",
I just realized this won't work with playtesting URLs, which are different ... I guess that's a reason to favor the API approach. But I don't want to spend too long on this. I think it's okay if playtesting URLs are treated as development for this purpose, but let's remember this in case it causes issues in the future.

2023-08-02 21:25 UTC, lilidworkin commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/dashboard-staging.justice-counts.org/i",
@alfonsogoberjr just want to confirm that you did see Michelle and Mahmoud's pointers about how to do this via the API [here](https://github.com/Recidiviz/justice-counts/pull/795#discussion_r1279926930), in case we have to change it later?

2023-08-02 23:27 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/dashboard-staging.justice-counts.org/i",
Confirmed

2023-08-03 00:05 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +    if (
Rebase gone wrong

2023-08-03 14:36 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
I'm curious about the pros/cons of this approach, where we make the backend API call here, as opposed to the approach in Publisher, where it's called in the API store [here](https://github.com/Recidiviz/justice-counts/blob/cb38e2e71d87388dfa9d4e3ce1bf30d32ecd024d/publisher/src/stores/API.ts#L50), and the result is stored in an `environment` property on that API to be referenced later. If we do it the way it is here, will we be calling the API more times than we need to? Like if we switch back and forth between different agencies, will we call the API each time?

2023-08-03 15:35 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
I tend to agree, because the API store lives in a React context, where it is mutable and only rendered once. 

There are more problems with this approach than just this, however. The endpoint is behind auth, so [this ticket](https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/22928) blocks this now.

2023-08-03 15:43 UTC, mxosman commented on agency-dashboard/src/utils/env.ts
> +  STAGING = "/dashboard-staging.justice-counts.org/i",
Good call about the playtesting URLs - didn't think of that. I think we'll also need to add a couple lines to the `/api/init` endpoint to add in an explicit check and return of the "production" environment (atm, we just have "unknown", "staging" and "local")

2023-08-03 15:43 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
Yeah, it's returning 401 unauthorized when called from agency dashboards. I was hoping it would work out of the box, but I remembered we never set up any auth handling in agency dashboards. Since that endpoint's auth decorator requires an auth token, would it make sense for us to add a new endpoint without the auth decorator just to get the environment?

2023-08-03 15:54 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
I can just mirror the Publisher API store pattern for the entire agency dashboard app, but this will take some time. Since the api endpoint needs to be changed, that pushes back the timeline for this specific ticket. Other agency dashboard work (such as [here](https://github.com/Recidiviz/justice-counts/pull/810/files)) can continue.

2023-08-03 15:55 UTC, mxosman commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
Since this app is mostly public - I'm not sure if it's worth the lift just to get the environment. I can work on the endpoint this morning to unblock.

2023-08-03 15:56 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
Just to make sure I understand -- doesn't this current approach (outside of the Auth store, but still calling the API endpoint) run into the same trouble?

2023-08-03 16:03 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
Yes, 100% agreed @mxosman ! If you could pair with @alfonsogoberjr on this that would be awesome, it shouldn't be hard at all.

2023-08-03 16:06 UTC, lilidworkin commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
Actually @mxosman I think @alfonsogoberjr should do the endpoint! But maybe you can just help him out?

2023-08-03 18:00 UTC, alfonsogoberjr commented on agency-dashboard/src/DashboardView/DashboardView.tsx
> +      setEnv(await getEnv());
It's done, try https://alfonsotest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/api/env

2023-08-03 18:12 UTC, lilidworkin reviewed
Looks right to me! Please add a test plan.

2023-08-03 19:22 UTC, mxosman commented on agency-dashboard/src/stores/API.ts
> +  }
Nice! Not for this PR, but might be worth making a note for us to either use this `request` method throughout and deprecate the `/networking.ts` helper, or if we're good with that helper, we could probably get rid of this method in the store and import the `request` from `/networking.ts`?

2023-08-03 19:50 UTC, alfonsogoberjr commented on agency-dashboard/src/stores/API.ts
> +  }
Oh I forgot about this duplication. Will consolidate

2023-08-03 21:11 UTC, lilidworkin approved these changes
@mxosman should probably also take a look, but this lgtm. Thanks for the detailed test plan!

2023-08-04 00:12 UTC, mxosman approved these changes
LGTM! Thanks, Alfonso!

2023-08-04 19:52 UTC, merged