Fix category page chart in recent mode
Recidiviz/justice-counts pull request #838
Opened 2023-08-08 17:20 UTC by ivan-kishko

## Description of the change

> Fix category page charts in recent mode to look like mini charts on agency page for consistency

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-08-08 21:18 UTC, alfonsogoberjr requested changes

2023-08-08 21:18 UTC, alfonsogoberjr commented on agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
> +                      data={transformDataForBarChart(
This will be affected by #810, specifically this part [here](https://github.com/Recidiviz/justice-counts/pull/810/files#diff-51ff4d22e39161ffdacfc0d4ad69243af7a86832415d0ed5afdfa2a95895b7ecR198) - this logic has been moved into a hook. 

Can you pull in the branch `792-part-2-capacity-and-costs-category` and update this PR?

2023-08-09 15:11 UTC, mxosman approved these changes
LGTM!

2023-08-09 17:23 UTC, mxosman approved these changes

2023-08-09 18:14 UTC, ivan-kishko commented on agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
> +                      data={transformDataForBarChart(
[32f2c04](https://github.com/Recidiviz/justice-counts/pull/838/commits/32f2c0419307f44d27dfc1a2017748a1df00ddbb)

2023-08-09 19:35 UTC, ivan-kishko commented
Sorry @mxosman I meant to ask for review from @alfonsogoberjr since he requested changes)

2023-08-10 04:18 UTC, alfonsogoberjr approved these changes

2023-08-10 04:18 UTC, alfonsogoberjr commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +                                  ? firstDatapointDate.getUTCFullYear()
good call using `Date.getUTCFullYear()`

2023-08-10 04:18 UTC, alfonsogoberjr commented on agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
> +          ? DataVizTimeRangesMap["5 Years Ago"]
Way better

2023-08-10 08:19 UTC, merged