Publisher nits
Recidiviz/justice-counts pull request #869
Opened 2023-08-18 10:34 UTC by ivan-kishko

## Description of the change

> Some nits for publisher

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #858 

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-08-18 10:48 UTC, ivan-kishko commented
@forrestkim00 @lilidworkin Some comments about nits
Nit #8 Forrest decided to exclude from list
Nit #3 The solution I came up with is use dummy data if data.length is 0 this dummy data has dates from Jan 2022 to Dec 2022. Also "No data for metric" Text is already centered, you can see that if you inspect chart container, it has some space below x-axis , so text is perfectly centered.
Nit #1 So about this. With recharts-to-png you cannot have legend metric name and padding inside image. Why? Because recharts-to-png converts only svg element to png. It does not care about containers, legends etc. So the solution might be to use html2canvas library (recharts-to-png is built on top of it). As far as I understood it takes element by id from page and converts it to png. So you can wrap inside data page metric name chart and legend and use this container to make png, BUT between metric name and chart there are filters. And since html2canvas takes all inside container they will be on a png. Maybe you can apply styles on download event click and then switch styles back, I read something about it but not sure for now is it possible and how it will affect UI, like you might see those changed styles for a split second or smth like that. 
All other nits are done.

2023-08-18 12:29 UTC, alfonsogoberjr commented on common/components/DataViz/DatapointsTableView.tsx
> -                    <Tooltip
No more tooltip?

2023-08-18 12:31 UTC, alfonsogoberjr requested changes

2023-08-18 12:31 UTC, alfonsogoberjr commented on common/components/DataViz/BarChart.tsx
> +    let dummyData: {
Can we move this into a test utils file? something like `generateBarChartDummyData`?

2023-08-18 17:16 UTC, mxosman commented on publisher/src/components/Reports/Reports.styles.tsx
> +    //}
nit: can delete

2023-08-18 17:21 UTC, mxosman commented
LGTM! Left a tiny nit in addition to the other feedback - will give others the final approval.

> Nit #1 So about this. With recharts-to-png you cannot have legend metric name and padding inside image. Why? Because recharts-to-png converts only svg element to png. It does not care about containers, legends etc. So the solution might be to use html2canvas library (recharts-to-png is built on top of it). As far as I understood it takes element by id from page and converts it to png. So you can wrap inside data page metric name chart and legend and use this container to make png, BUT between metric name and chart there are filters. And since html2canvas takes all inside container they will be on a png. Maybe you can apply styles on download event click and then switch styles back, I read something about it but not sure for now is it possible and how it will affect UI, like you might see those changed styles for a split second or smth like that. All other nits are done.

Ah - great suggestion! Thank you for this. I'll make a task to explore this.

2023-08-18 17:40 UTC, ivan-kishko commented on common/components/DataViz/DatapointsTableView.tsx
> -                    <Tooltip
nit 4 in task)

2023-08-18 17:44 UTC, ivan-kishko commented on common/components/DataViz/BarChart.tsx
> +    let dummyData: {
[2d9fa0f](https://github.com/Recidiviz/justice-counts/pull/869/commits/2d9fa0fe171c7ff3f7aa205a27771de4382a6679)

2023-08-18 17:47 UTC, mxosman approved these changes

2023-08-21 18:52 UTC, alfonsogoberjr approved these changes
LGTM

2023-08-21 22:08 UTC, mxosman commented on publisher/src/components/Reports/Reports.styles.tsx
> +    &:nth-child(3) {
We could! Ivan's no longer on the project, but we could make an enhancement task to target these more specific than `nth-child`. Since it's styled-components might be an easier time interpolating components vs. using classes (we currently don't use the classnames convention anywhere in our codebase since we're using styled-components vs. css files)?

2023-08-21 22:11 UTC, mxosman commented
@alfonsogoberjr - I'm going to go ahead and merge this in since Ivan is no longer on the project and all feedback has been addressed! (I figured we can just make a task for your latest feedback since it's more involved)

2023-08-21 22:11 UTC, merged