[#851] Add law enforcement as available system
Recidiviz/justice-counts pull request #870
Opened 2023-08-18 12:28 UTC by alfonsogoberjr

## Description of the change

Add law enforcement as available system for Agency Dash

## Related issues

Closes #851

## Test Plan

https://alfonsotest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/agency/law-enforcement

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2023-08-18 13:21 UTC, lilidworkin reviewed
Thanks @alfonsogoberjr ! A couple things:

* Add a test plan
* There was a bullet point in the ticket that said "Add "Law Enforcement [DEMO]" to the allowlist (this agency should already exist and have data -- if it doesn't have multiple years of worth of data for the Capacity and Cost metrics, go ahead and add)". Basically, we need to make sure that we have a link we can share with Stephanie that she can use in her demo on Tues. You should coordinate with her (can find her in #jc-tech-chat) and @jwhrec to get the exact requirements for that.

Also, did you see @jwhrec 's message in Slack and updates to the ticket that said we should ungate for all sectors?

2023-08-18 23:03 UTC, mxosman commented on agency-dashboard/src/utils/allowlist.ts
> +  "Law Enforcement [DEMO]": true,
I have a feeling that the `availableSystems` in `AgencyOverview` are actually the thing driving which agency is allowed to be viewed. It seems I can access other agencies outside of this list, but only if they belong to a system within the `availableSystems`.

2023-08-18 23:03 UTC, mxosman commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +const availableSystems: AgencySystems[] = ["PRISONS", "LAW_ENFORCEMENT"];
nit: when I'm in a law enforcement agency it still loads a Prisons chip with no content.

<img width="528" alt="Screenshot 2023-08-18 at 5 43 38 PM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/964a62b7-7e8e-4a98-b2b2-9cd743c63ce9">

2023-08-18 23:21 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/allowlist.ts
> +  "Law Enforcement [DEMO]": true,
Yes I updated this

2023-08-18 23:21 UTC, alfonsogoberjr commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +const availableSystems: AgencySystems[] = ["PRISONS", "LAW_ENFORCEMENT"];
Fixed

2023-08-19 02:04 UTC, lilidworkin requested changes
@alfonsogoberjr your playtesting link is not working for me, did it work for you? Also, the playtesting link goes to the Law Enforcement agency, but the agency you added to the allowlist is Law Enforcement [Demo]. Which do you intend to use for the demo? And have you ensured that whichever one you choose has appropriate amounts of fake data?

2023-08-19 02:04 UTC, lilidworkin commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> -  const metricsByAvailableCategoriesAndSystems = agencyDataStore.metrics.filter(
Don't we still need to check against available _categories_?

2023-08-19 02:04 UTC, lilidworkin commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +  if (!agencyDataStore.agency) return <NotFound />;
Don't we still need to check if the agency has no data?

2023-08-19 02:04 UTC, lilidworkin commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +            {pipe(
This feels way less readable to me than the way it was before. I don't understand the benefit of rewriting this using ramda. First of all, why do we need to filter the agency systems to not include null? It will never include null. Why do we need to use uniq? This list will always be deduplicated. Neither is necessary -- we should just map over the list as before.

2023-08-19 02:04 UTC, lilidworkin commented on agency-dashboard/src/utils/allowlist.ts
> +  "Law Enforcement [DEMO]": true,
I think, if I understand correctly, that @mxosman is saying that the allowlist is not being used? In other words, agencies not on the allowlist are still being shown? If so, that's a problem.

2023-08-21 15:05 UTC, alfonsogoberjr commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +            {pipe(
Wow, someone's angry.

There were null values in the array that weren't accounted for. But I apparently have no idea what I'm doing, so I will defer to you and your infinite wisdom.

2023-08-21 15:05 UTC, alfonsogoberjr commented on agency-dashboard/src/utils/allowlist.ts
> +  "Law Enforcement [DEMO]": true,
This is being updated.

2023-08-21 15:06 UTC, alfonsogoberjr commented on agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> +  const [agencySystems, setAgencySystems] = useState<AgencySystems[]>(
I would try explaining this, but I know it would fall on deaf ears.

2023-08-21 15:27 UTC, lilidworkin requested changes
Hey @alfonsogoberjr , thanks for working on this. There are still a few issues with this PR. Since CSG needs this tomorrow, I went ahead and put up a solution that I think should work here: https://github.com/Recidiviz/justice-counts/pull/879

2023-08-21 15:30 UTC, alfonsogoberjr commented
@lilidworkin has her own PR to prove a point, point proven

2023-08-21 15:30 UTC, closed without merging